import js from "@eslint/js";
import { defineConfig, globalIgnores } from "eslint/config";
import prettier from "eslint-config-prettier/flat";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";
import tseslint from "typescript-eslint";

export default defineConfig([
  // dist is build output; types.ts is generated by `pnpm generate:api` from the
  // committed OpenAPI snapshot and is never edited by hand.
  globalIgnores(["dist", "src/api/types.ts"]),
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommendedTypeChecked,
      // The flat namespace: the plugin still ships eslintrc-shaped configs
      // under the bare keys.
      reactHooks.configs.flat["recommended-latest"],
      reactRefresh.configs.vite,
      // Last, so formatting rules never fight Prettier.
      prettier,
    ],
    rules: {
      // A leading underscore is the house way of saying "this parameter is
      // here for its position or its type, not to be read".
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_" },
      ],
    },
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
]);
