minimumReleaseAgeExclude:
  - "@codemirror/search@6.7.2"
  - "@typescript-eslint/eslint-plugin@8.70.0"
  - "@typescript-eslint/parser@8.70.0"
  - "@typescript-eslint/project-service@8.70.0"
  - "@typescript-eslint/scope-manager@8.70.0"
  - "@typescript-eslint/tsconfig-utils@8.70.0"
  - "@typescript-eslint/type-utils@8.70.0"
  - "@typescript-eslint/types@8.70.0"
  - "@typescript-eslint/typescript-estree@8.70.0"
  - "@typescript-eslint/utils@8.70.0"
  - "@typescript-eslint/visitor-keys@8.70.0"
  - typescript-eslint@8.70.0
overrides:
  js-yaml: ^4.3.2
  "lodash-es@<4.18.0": ^4.18.1
  "nanoid@<3.3.18": ^3.3.18
