//! Endpoint tests for the admin settings surface: the GitHub connection
//! status and its device-flow poll, the two connect paths and disconnect,
//! plus domain lifecycle - create in all three modes and unregister.
//!
//! A fresh, smaller fixture rather than a share of `rest_write_api.rs`'s: the
//! engine here is built with the token store pinned into the temp dir and a
//! stub [`support::StubConnectAuth`], so nothing in this suite can read, write
//! or delete the developer's real GitHub credential, and `github.enabled` is
//! a per-test option because the settings screen's own contract is that
//! connecting turns the feature on.

mod support;

use std::sync::Arc;
use std::sync::atomic::AtomicUsize;

use crystalline_core::config::{
    AuthConfig, DomainEntry, GitHubConfig, GlobalConfig, OriginConfig, ResponseFormat,
    ServiceConfig,
};
use crystalline_index::TursoStore;
use crystalline_service::Engine;
use crystalline_service::daemon::http_router;
use crystalline_service::engine::ConnectAuth;
use crystalline_service::rest::{AuthStore, Role};
use tokio::sync::Mutex;

const ALPHA: &str = "---\ntype: engram\ntitle: Alpha\npermalink: alpha\ntags:\n  - eng\nstatus: stable\nrecorded_at: 2026-01-01\n---\n\n# Alpha\n\nA rule about alpha.\n";

/// The domain's `log.md`. Reserved by OKF but never generated by anything, so
/// whatever a domain holds here is user content that no refresh would bring
/// back - which is what makes it the sharp case for the reserved-name screen.
const LOG: &str = "# Log\n\n- 2026-01-01 the domain was opened\n";

/// What an admin-test server varies.
#[derive(Default)]
struct Options {
    /// Serve read-only: every mutation is refused, reads are not.
    read_only: bool,
    /// Start with `github.enabled` already on.
    github: bool,
    /// The connect double this engine authenticates through. Defaults to
    /// `StubConnectAuth::accepting("octo")`, which validates any token and
    /// runs no device flow.
    connect_auth: Option<Arc<dyn ConnectAuth>>,
    /// The forge a team-domain registration downloads from. Set for the
    /// github-mode tests so nothing here dials github.com; unset means no
    /// override, which is fine for every test that never reaches a provider.
    origin_provider: Option<Arc<support::MockProvider>>,
    /// Register a domain `kb` that carries a GitHub origin in the config
    /// without ever downloading one. The only way to address a team domain on
    /// an instance where `github.enabled` is off, which is the state the sync
    /// endpoints' 409 exists for.
    origin_domain: bool,
}

struct Fixture {
    addr: std::net::SocketAddr,
    _tmp: tempfile::TempDir,
}

async fn serve(opts: Options) -> Fixture {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path().to_path_buf();
    let mut cfg = GlobalConfig {
        // Pin the domains root inside the temp dir so nothing this suite
        // creates can land in a real home folder.
        domains_root: Some(root.join("domains-root")),
        auth: Some(AuthConfig {
            trusted_header: None,
            anonymous: Some(false),
            max_users: None,
        }),
        github: opts.github.then(|| GitHubConfig {
            enabled: Some(true),
            ..GitHubConfig::default()
        }),
        ..GlobalConfig::default()
    };
    let dir = root.join("eng");
    std::fs::create_dir_all(&dir).unwrap();
    std::fs::write(
        dir.join("MANIFEST.md"),
        "---\ntype: manifest\ntitle: eng\npermalink: manifest\ntags:\n  - manifest\nstatus: current\nrecorded_at: 2026-01-01\n---\n\n# eng\n\n## Scope\n\n- Everything about eng\n\n## When to Use\n\n- Route here for eng questions\n",
    )
    .unwrap();
    std::fs::write(dir.join("alpha.md"), ALPHA).unwrap();
    // A log the domain keeps and nothing regenerates: what the reserved-name
    // screen is protecting.
    std::fs::write(dir.join("log.md"), LOG).unwrap();
    cfg.domains
        .insert("eng".to_string(), DomainEntry::file(dir));
    if opts.origin_domain {
        let team = root.join("kb");
        std::fs::create_dir_all(&team).unwrap();
        std::fs::write(
            team.join("MANIFEST.md"),
            "---\ntype: manifest\ntitle: kb\npermalink: manifest\ntags:\n  - manifest\nstatus: current\nrecorded_at: 2026-01-01\n---\n\n# kb\n\n## Scope\n\n- shared knowledge\n\n## When to Use\n\n- Route here for team questions\n",
        )
        .unwrap();
        cfg.domains.insert(
            "kb".to_string(),
            DomainEntry {
                origin: Some(OriginConfig {
                    repo: "acme/kb".to_string(),
                    path: None,
                    branch: None,
                    poll_secs: None,
                }),
                ..DomainEntry::file(team)
            },
        );
    }
    cfg.service = Some(ServiceConfig {
        response_format: Some(ResponseFormat::Json),
        read_only: Some(opts.read_only),
        ..ServiceConfig::default()
    });
    let config_path = root.join("config.yaml");
    crystalline_core::config::save_yaml(&config_path, &cfg).unwrap();
    let store = TursoStore::open_in_memory().await.unwrap();
    let connect_auth: Arc<dyn ConnectAuth> = opts
        .connect_auth
        .unwrap_or_else(|| Arc::new(support::StubConnectAuth::accepting("octo")));
    // Both overrides are load-bearing, not tidiness: without the token-store
    // dir a disconnect here would delete the developer's REAL keychain GitHub
    // token, and without the stub a connect would dial github.com.
    // The origins dir is pinned for the same reason as the token store: a
    // team-domain registration writes origin state, and it must land in the
    // temp dir rather than in the developer's real state directory.
    let mut engine = Engine::new(Arc::new(Mutex::new(store)), cfg, None, Some(config_path))
        .with_read_only(opts.read_only)
        .with_token_store_dir(root.join("tokens"))
        .with_connect_auth(connect_auth)
        .with_origins_dir(root.join("origins"));
    if let Some(provider) = opts.origin_provider {
        engine = engine.with_origin_provider(provider);
    }
    let engine = Arc::new(engine);
    engine.sync(None).await.unwrap();

    let auth = Arc::new(
        AuthStore::open(&tmp.path().join("web-auth.db"))
            .await
            .unwrap(),
    );
    // One account per role, so every gate has a caller to refuse.
    auth.add_user("root", "Root", None, Role::Admin, "rootpw")
        .await
        .unwrap();
    auth.add_user("eddy", "Eddy", None, Role::Editor, "eddypw")
        .await
        .unwrap();
    auth.add_user("vera", "Vera", None, Role::Viewer, "verapw")
        .await
        .unwrap();

    let router = http_router(
        engine,
        Arc::new(AtomicUsize::new(0)),
        &[],
        auth.clone(),
        None,
    )
    .unwrap();
    let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    listener.set_nonblocking(true).unwrap();
    let addr = listener.local_addr().unwrap();
    tokio::spawn(async move {
        let listener = tokio::net::TcpListener::from_std(listener).unwrap();
        // Served the way `run_http` serves it, connect info included: the peer
        // address the first-run setup route reads lives in the extensions this
        // adds, and a plain router would leave it missing.
        axum::serve(
            listener,
            router.into_make_service_with_connect_info::<std::net::SocketAddr>(),
        )
        .await
        .unwrap();
    });
    Fixture { addr, _tmp: tmp }
}

fn client() -> reqwest::Client {
    reqwest::Client::builder().no_proxy().build().unwrap()
}

/// Log in, returning (session cookie value, csrf token).
async fn login(addr: std::net::SocketAddr, name: &str, password: &str) -> (String, String) {
    let resp = client()
        .post(format!("http://{addr}/api/v1/auth/login"))
        .json(&serde_json::json!({"name": name, "password": password}))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 200, "login as {name} must succeed");
    let cookie = resp
        .headers()
        .get_all(reqwest::header::SET_COOKIE)
        .iter()
        .filter_map(|v| v.to_str().ok())
        .find(|v| v.starts_with("fluid_session="))
        .and_then(|v| v.split(';').next())
        .and_then(|v| v.strip_prefix("fluid_session="))
        .unwrap()
        .to_string();
    let body: serde_json::Value = resp.json().await.unwrap();
    (cookie, body["csrf"].as_str().unwrap().to_string())
}

/// A request carrying a session and its token, the browser shape.
fn as_session(
    addr: std::net::SocketAddr,
    method: reqwest::Method,
    path: &str,
    session: &(String, String),
) -> reqwest::RequestBuilder {
    client()
        .request(method, format!("http://{addr}{path}"))
        .header("cookie", format!("fluid_session={}", session.0))
        .header("x-csrf-token", &session.1)
}

/// Local create is name-only: the domain lands under the server's domains
/// root, scaffolded and listed; the response says where. Registration
/// refusals are honest statuses: 409 for a taken name, 422 for a name that
/// could escape the root.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn a_local_domain_is_created_under_the_domains_root() {
    let fx = serve(Options::default()).await;
    let admin = login(fx.addr, "root", "rootpw").await;

    let resp = as_session(fx.addr, reqwest::Method::POST, "/api/v1/domains", &admin)
        .json(&serde_json::json!({"mode": "local", "name": "notes"}))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 201);
    let body: serde_json::Value = resp.json().await.unwrap();
    assert_eq!(body["domain"], "notes");
    let root = body["root"].as_str().unwrap();
    assert!(
        root.contains("domains-root"),
        "under the pinned root: {root}"
    );
    assert!(std::path::Path::new(root).join("MANIFEST.md").exists());

    // Listed for everyone now.
    let listing = as_session(fx.addr, reqwest::Method::GET, "/api/v1/domains", &admin)
        .send()
        .await
        .unwrap();
    assert!(listing.text().await.unwrap().contains("notes"));

    // Same name again: conflict, not a stack trace.
    let dup = as_session(fx.addr, reqwest::Method::POST, "/api/v1/domains", &admin)
        .json(&serde_json::json!({"mode": "virtual", "name": "notes"}))
        .send()
        .await
        .unwrap();
    assert_eq!(dup.status(), 409);

    // Names that could escape or break Windows are refused up front.
    for bad in ["../up", "a/b", "a\\b", "a:b", ".hidden", "a b", "", "   "] {
        let resp = as_session(fx.addr, reqwest::Method::POST, "/api/v1/domains", &admin)
            .json(&serde_json::json!({"mode": "local", "name": bad}))
            .send()
            .await
            .unwrap();
        assert_eq!(resp.status(), 422, "{bad:?} must be refused");
    }
}

/// Virtual create works with a name alone; mode github without a connection
/// is a 409 that points at the settings screen.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn virtual_creates_and_disconnected_github_mode_is_a_conflict() {
    let fx = serve(Options::default()).await;
    let admin = login(fx.addr, "root", "rootpw").await;

    let resp = as_session(fx.addr, reqwest::Method::POST, "/api/v1/domains", &admin)
        .json(&serde_json::json!({"mode": "virtual", "name": "scratchpad"}))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 201);

    let team = as_session(fx.addr, reqwest::Method::POST, "/api/v1/domains", &admin)
        .json(&serde_json::json!({"mode": "github", "repo": "acme/kb"}))
        .send()
        .await
        .unwrap();
    assert_eq!(team.status(), 409);
    let problem: serde_json::Value = team.json().await.unwrap();
    assert!(
        problem["detail"]
            .as_str()
            .unwrap()
            .to_lowercase()
            .contains("settings"),
        "the refusal points at the fix: {problem}"
    );

    let nonsense = as_session(fx.addr, reqwest::Method::POST, "/api/v1/domains", &admin)
        .json(&serde_json::json!({"mode": "zeppelin", "name": "x"}))
        .send()
        .await
        .unwrap();
    assert_eq!(nonsense.status(), 422);
}

/// A team domain registers under the name the validator handed back, not the
/// raw one the body carried: `origin_add` uses what it is given verbatim as
/// the config key AND as the folder segment under the domains root, so a
/// padded name would otherwise register a domain called "\tteam " with an
/// on-disk folder to match - the very thing the name check exists to stop.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn a_team_domain_registers_under_the_trimmed_name() {
    let mock = Arc::new(support::MockProvider::new());
    let commit = mock.add_commit(std::collections::BTreeMap::from([(
        "MANIFEST.md".to_string(),
        b"---\ntype: manifest\ntitle: Team\npermalink: manifest\ntags:\n  - manifest\nstatus: current\nrecorded_at: 2026-01-01\n---\n\n# Team\n\n## Scope\n\n- shared knowledge\n\n## When to Use\n\n- Route here for team questions\n".to_vec(),
    )]));
    mock.set_branch("main", &commit);
    let fx = serve(Options {
        github: true,
        origin_provider: Some(mock),
        ..Options::default()
    })
    .await;
    let admin = login(fx.addr, "root", "rootpw").await;

    // A credential has to be on file for `github_ready` to let the mode
    // through; the stub validates any token without leaving the machine.
    let connected = as_session(
        fx.addr,
        reqwest::Method::POST,
        "/api/v1/settings/github/token",
        &admin,
    )
    .json(&serde_json::json!({"token": "pat-secret-123"}))
    .send()
    .await
    .unwrap();
    assert_eq!(connected.status(), 200);

    let created = as_session(fx.addr, reqwest::Method::POST, "/api/v1/domains", &admin)
        .json(&serde_json::json!({"mode": "github", "repo": "acme/kb", "name": "\tteam "}))
        .send()
        .await
        .unwrap();
    assert_eq!(created.status(), 201);
    let body: serde_json::Value = created.json().await.unwrap();
    assert_eq!(
        body["domain"], "team",
        "the registered name is the trimmed one"
    );
    let root = body["root"].as_str().unwrap();
    assert!(root.ends_with("team"), "and so is the folder: {root}");
    assert!(
        fx._tmp
            .path()
            .join("domains-root/team/MANIFEST.md")
            .exists(),
        "the download landed under the pinned domains root"
    );

    // And the listing knows it by the trimmed name only.
    let listing = as_session(fx.addr, reqwest::Method::GET, "/api/v1/domains", &admin)
        .send()
        .await
        .unwrap()
        .text()
        .await
        .unwrap();
    assert!(listing.contains("\"team\""), "{listing}");
    assert!(
        !listing.contains("\\tteam"),
        "no padded name was ever registered: {listing}"
    );
}

/// A team instance: GitHub on, a stub-validated credential already on file
/// and a mock forge serving `acme/kb` at the tracked branch head, so nothing
/// this fixture's tests do - registering, reading status, pulling - ever
/// leaves the machine or touches the developer's real GitHub connection.
async fn serve_team() -> Fixture {
    let mock = Arc::new(support::MockProvider::new());
    let commit = mock.add_commit(std::collections::BTreeMap::from([
        (
            "MANIFEST.md".to_string(),
            b"---\ntype: manifest\ntitle: kb\npermalink: manifest\ntags:\n  - manifest\nstatus: current\nrecorded_at: 2026-01-01\n---\n\n# kb\n\n## Scope\n\n- shared knowledge\n\n## When to Use\n\n- Route here for team questions\n".to_vec(),
        ),
        (
            "shared.md".to_string(),
            b"---\ntype: engram\ntitle: Shared\npermalink: shared\ntags:\n  - team\nstatus: stable\nrecorded_at: 2026-01-01\n---\n\n# Shared\n\nA rule the team agreed on.\n".to_vec(),
        ),
    ]));
    mock.set_branch("main", &commit);
    let fx = serve(Options {
        github: true,
        origin_provider: Some(mock),
        ..Options::default()
    })
    .await;
    let admin = login(fx.addr, "root", "rootpw").await;
    let connected = as_session(
        fx.addr,
        reqwest::Method::POST,
        "/api/v1/settings/github/token",
        &admin,
    )
    .json(&serde_json::json!({"token": "pat-secret-123"}))
    .send()
    .await
    .unwrap();
    assert_eq!(
        connected.status(),
        200,
        "the team fixture needs a credential on file before any registration"
    );
    fx
}

/// The team fixture registers acme/kb through POST /domains, and the sync
/// endpoints serve its status and pull updates. Non-team and unknown
/// domains get the honest statuses the spec pins.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn team_sync_status_and_sync_now_walk_the_contract() {
    let fx = serve_team().await;
    let admin = login(fx.addr, "root", "rootpw").await;

    let created = as_session(fx.addr, reqwest::Method::POST, "/api/v1/domains", &admin)
        .json(&serde_json::json!({"mode": "github", "repo": "acme/kb"}))
        .send()
        .await
        .unwrap();
    assert_eq!(created.status(), 201, "{}", created.text().await.unwrap());

    let status = as_session(
        fx.addr,
        reqwest::Method::GET,
        "/api/v1/domains/kb/sync",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(status.status(), 200);
    let status: serde_json::Value = status.json().await.unwrap();
    assert_eq!(status["mode"], "github");
    assert_eq!(status["domain"], "kb");
    assert_eq!(status["repo"], "acme/kb");
    assert!(status["branch"].is_string());
    assert!(
        status.get("local_changes").is_some(),
        "the card's pending count: {status}"
    );
    assert!(
        status.get("domains").is_none(),
        "one domain was asked for, so one domain is answered, flat: {status}"
    );

    let pulled = as_session(
        fx.addr,
        reqwest::Method::POST,
        "/api/v1/domains/kb/sync",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(pulled.status(), 200, "{}", pulled.text().await.unwrap());
    let pulled: serde_json::Value = pulled.json().await.unwrap();
    assert_eq!(pulled["domain"], "kb");
    assert_eq!(
        pulled["up_to_date"], true,
        "nothing moved on the mock forge since the registration: {pulled}"
    );

    // Non-team domain: the status resource does not exist (GET), the action
    // conflicts (POST). Both details name the reason.
    let non_team_get = as_session(
        fx.addr,
        reqwest::Method::GET,
        "/api/v1/domains/eng/sync",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(non_team_get.status(), 404);
    let problem: serde_json::Value = non_team_get.json().await.unwrap();
    assert!(
        problem["detail"].as_str().unwrap().contains("team"),
        "the 404 says why, so the UI can tell it from an unknown domain: {problem}"
    );
    let non_team_post = as_session(
        fx.addr,
        reqwest::Method::POST,
        "/api/v1/domains/eng/sync",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(non_team_post.status(), 409);
    let problem: serde_json::Value = non_team_post.json().await.unwrap();
    assert!(
        problem["detail"].as_str().unwrap().contains("team"),
        "and so does the conflict: {problem}"
    );

    // Unknown domain: 404 on both.
    let ghost = as_session(
        fx.addr,
        reqwest::Method::GET,
        "/api/v1/domains/ghost/sync",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(ghost.status(), 404);
    let ghost_post = as_session(
        fx.addr,
        reqwest::Method::POST,
        "/api/v1/domains/ghost/sync",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(ghost_post.status(), 404, "no such resource to sync either");

    // The GET is admin-only too (the write matrix covers only the POST).
    for (name, pw) in [("eddy", "eddypw"), ("vera", "verapw")] {
        let session = login(fx.addr, name, pw).await;
        let resp = as_session(
            fx.addr,
            reqwest::Method::GET,
            "/api/v1/domains/kb/sync",
            &session,
        )
        .send()
        .await
        .unwrap();
        assert_eq!(resp.status(), 403, "{name} must not read sync status");
    }
}

/// GitHub switched off on an instance that still has a team domain
/// registered: both endpoints answer 409 naming the settings screen, rather
/// than the bare 422 the engine's own NotEnabled would produce - the card
/// shows that sentence in place of its rows.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn a_disabled_github_names_the_fix_on_both_sync_endpoints() {
    let fx = serve(Options {
        origin_domain: true,
        ..Options::default()
    })
    .await;
    let admin = login(fx.addr, "root", "rootpw").await;

    for method in [reqwest::Method::GET, reqwest::Method::POST] {
        let resp = as_session(fx.addr, method.clone(), "/api/v1/domains/kb/sync", &admin)
            .send()
            .await
            .unwrap();
        assert_eq!(resp.status(), 409, "{method} on a disabled instance");
        let problem: serde_json::Value = resp.json().await.unwrap();
        assert!(
            problem["detail"]
                .as_str()
                .unwrap()
                .to_lowercase()
                .contains("settings"),
            "the refusal points at the fix: {problem}"
        );
    }
}

/// The read-only ruling on this pair: the status is a pure read and stays
/// served (a read-only mirror still shows its sync card), the pull is a
/// mutation of this instance's copy and is refused. The GET is asserted as
/// "not 403" rather than as a 200, because it is the 403 that would appear if
/// anyone ever added `refuse_read_only` to it.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn read_only_serves_the_status_and_refuses_the_pull() {
    let ro = serve(Options {
        read_only: true,
        github: true,
        ..Options::default()
    })
    .await;
    let admin = login(ro.addr, "root", "rootpw").await;

    let status = as_session(
        ro.addr,
        reqwest::Method::GET,
        "/api/v1/domains/eng/sync",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(
        status.status(),
        404,
        "the read reached the domain check instead of being refused outright"
    );

    let pull = as_session(
        ro.addr,
        reqwest::Method::POST,
        "/api/v1/domains/eng/sync",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(
        pull.status(),
        403,
        "read_only refuses the pull before anything else is decided"
    );
}

/// Unregister: the registration and index rows go, the files stay, and the
/// response carries the files_kept flag the confirmation wording leans on.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn unregister_answers_with_files_kept_and_the_domain_vanishes() {
    let fx = serve(Options::default()).await;
    let admin = login(fx.addr, "root", "rootpw").await;

    let resp = as_session(
        fx.addr,
        reqwest::Method::DELETE,
        "/api/v1/domains/eng",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(resp.status(), 200);
    let body: serde_json::Value = resp.json().await.unwrap();
    assert_eq!(body["files_kept"], true);
    assert_eq!(body["rooms_closed"], 0, "nobody was co-editing this one");
    assert!(
        fx._tmp.path().join("eng/alpha.md").exists(),
        "files stay on disk"
    );

    let listing = as_session(fx.addr, reqwest::Method::GET, "/api/v1/domains", &admin)
        .send()
        .await
        .unwrap();
    assert!(!listing.text().await.unwrap().contains("\"eng\""));

    let again = as_session(
        fx.addr,
        reqwest::Method::DELETE,
        "/api/v1/domains/eng",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(again.status(), 404);

    // The virtual arm: a database-backed domain's rows ARE its knowledge, so
    // its unregistration says files_kept: false and the confirmation wording
    // the UI shows has to differ. Same route, opposite flag.
    let made = as_session(fx.addr, reqwest::Method::POST, "/api/v1/domains", &admin)
        .json(&serde_json::json!({"mode": "virtual", "name": "ephemeral"}))
        .send()
        .await
        .unwrap();
    assert_eq!(made.status(), 201);
    let gone = as_session(
        fx.addr,
        reqwest::Method::DELETE,
        "/api/v1/domains/ephemeral",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(gone.status(), 200);
    let gone: serde_json::Value = gone.json().await.unwrap();
    assert_eq!(gone["files_kept"], false, "there are no files to keep");
}

/// The admin gate on the whole settings surface: viewer and editor are 403
/// on the GET too (the write matrix only covers unsafe methods). read_only
/// serves the status read - a pure read - and refuses the mutations.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn github_settings_are_admin_only_and_read_only_refuses_mutations() {
    let fx = serve(Options {
        github: true,
        ..Options::default()
    })
    .await;
    for (name, pw) in [("eddy", "eddypw"), ("vera", "verapw")] {
        let session = login(fx.addr, name, pw).await;
        let resp = as_session(
            fx.addr,
            reqwest::Method::GET,
            "/api/v1/settings/github",
            &session,
        )
        .send()
        .await
        .unwrap();
        assert_eq!(resp.status(), 403, "{name} must not read the connection");
    }
    let ro = serve(Options {
        read_only: true,
        github: true,
        ..Options::default()
    })
    .await;
    let admin = login(ro.addr, "root", "rootpw").await;
    let resp = as_session(
        ro.addr,
        reqwest::Method::GET,
        "/api/v1/settings/github",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(
        resp.status(),
        200,
        "the status is a pure read; read_only serves it"
    );
    let resp = as_session(
        ro.addr,
        reqwest::Method::POST,
        "/api/v1/settings/github/connect",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(resp.status(), 403, "read_only refuses the mutations");
}

/// The other two mutations under read_only, at the route level rather than by
/// analogy: a PAT connect and a disconnect are refused by this layer before
/// the engine is asked, so a read-only instance can neither acquire nor
/// forget a credential over HTTP.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn read_only_refuses_the_token_and_disconnect_routes() {
    let ro = serve(Options {
        read_only: true,
        github: true,
        ..Options::default()
    })
    .await;
    let admin = login(ro.addr, "root", "rootpw").await;

    let stored = as_session(
        ro.addr,
        reqwest::Method::POST,
        "/api/v1/settings/github/token",
        &admin,
    )
    .json(&serde_json::json!({"token": "pat-secret-123"}))
    .send()
    .await
    .unwrap();
    assert_eq!(stored.status(), 403, "read_only stores no credential");

    let gone = as_session(
        ro.addr,
        reqwest::Method::DELETE,
        "/api/v1/settings/github",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(gone.status(), 403, "read_only forgets none either");
}

/// PAT connect end to end: the status flips to connected, names the account
/// and the store kind, and the token appears in no response body. Disconnect
/// flips it back.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn a_pat_connects_and_disconnect_forgets_it() {
    let fx = serve(Options {
        github: true,
        ..Options::default()
    })
    .await;
    let admin = login(fx.addr, "root", "rootpw").await;

    let before = as_session(
        fx.addr,
        reqwest::Method::GET,
        "/api/v1/settings/github",
        &admin,
    )
    .send()
    .await
    .unwrap();
    let before: serde_json::Value = before.json().await.unwrap();
    assert_eq!(before["connected"], false);

    let connected = as_session(
        fx.addr,
        reqwest::Method::POST,
        "/api/v1/settings/github/token",
        &admin,
    )
    .json(&serde_json::json!({"token": "pat-secret-123"}))
    .send()
    .await
    .unwrap();
    assert_eq!(connected.status(), 200);
    let body = connected.text().await.unwrap();
    assert!(
        !body.contains("pat-secret-123"),
        "write-only means write-only: {body}"
    );
    let body: serde_json::Value = serde_json::from_str(&body).unwrap();
    assert_eq!(body["connected"], true);
    assert_eq!(body["user"], "octo");
    assert_eq!(body["token_store"], "file");
    assert_eq!(
        body["enabled"], true,
        "the Connect intent enables the feature"
    );

    let gone = as_session(
        fx.addr,
        reqwest::Method::DELETE,
        "/api/v1/settings/github",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(gone.status(), 200);
    let gone: serde_json::Value = gone.json().await.unwrap();
    assert_eq!(gone["connected"], false);
}

/// A PAT connect on an instance where the feature was never turned on: the
/// Connect intent enables it, so the screen never has to ask twice.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn connecting_turns_the_feature_on() {
    let fx = serve(Options::default()).await;
    let admin = login(fx.addr, "root", "rootpw").await;

    let before = as_session(
        fx.addr,
        reqwest::Method::GET,
        "/api/v1/settings/github",
        &admin,
    )
    .send()
    .await
    .unwrap();
    let before: serde_json::Value = before.json().await.unwrap();
    assert_eq!(before["enabled"], false, "off until someone connects");

    let connected = as_session(
        fx.addr,
        reqwest::Method::POST,
        "/api/v1/settings/github/token",
        &admin,
    )
    .json(&serde_json::json!({"token": "pat-secret-123"}))
    .send()
    .await
    .unwrap();
    assert_eq!(connected.status(), 200);
    let connected: serde_json::Value = connected.json().await.unwrap();
    assert_eq!(connected["enabled"], true);
    assert_eq!(connected["connected"], true);
}

/// An empty token is refused before anything is validated or stored.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn an_empty_token_is_refused() {
    let fx = serve(Options {
        github: true,
        ..Options::default()
    })
    .await;
    let admin = login(fx.addr, "root", "rootpw").await;

    let resp = as_session(
        fx.addr,
        reqwest::Method::POST,
        "/api/v1/settings/github/token",
        &admin,
    )
    .json(&serde_json::json!({"token": "   "}))
    .send()
    .await
    .unwrap();
    assert_eq!(resp.status(), 422);

    let after = as_session(
        fx.addr,
        reqwest::Method::GET,
        "/api/v1/settings/github",
        &admin,
    )
    .send()
    .await
    .unwrap();
    let after: serde_json::Value = after.json().await.unwrap();
    assert_eq!(after["connected"], false, "nothing was stored");
}

/// Disconnecting an instance that was never connected is a success, not a
/// 404: `DELETE` says "make it so there is no connection", and there is not
/// one. The settings screen can therefore offer the button without first
/// having to decide whether it would be legal.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn disconnecting_twice_is_a_success_both_times() {
    let fx = serve(Options {
        github: true,
        ..Options::default()
    })
    .await;
    let admin = login(fx.addr, "root", "rootpw").await;

    for round in 0..2 {
        let gone = as_session(
            fx.addr,
            reqwest::Method::DELETE,
            "/api/v1/settings/github",
            &admin,
        )
        .send()
        .await
        .unwrap();
        assert_eq!(gone.status(), 200, "round {round}");
        let gone: serde_json::Value = gone.json().await.unwrap();
        assert_eq!(gone["connected"], false, "round {round}");
        assert!(gone["user"].is_null(), "round {round}");
        assert!(gone["token_store"].is_null(), "round {round}");
    }
}

/// The device flow over REST: 202 with the short code and verification URL,
/// GET is the poll, and a failed flow's error is reported exactly once.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn the_device_flow_polls_over_get_and_reports_failure_once() {
    // The stub's device arm hands out code "ABCD-1234" at
    // https://github.example/device; its background wait BLOCKS on a Notify
    // until the test releases it, then fails with "authorization denied".
    // The gate is load-bearing: start_device_connect SPAWNS the flow task,
    // so an instantly-failing stub could land (and clear) the outcome
    // before the 202 body is even read.
    let (auth, release) = support::StubConnectAuth::denying("authorization denied");
    let fx = serve(Options {
        github: true,
        connect_auth: Some(std::sync::Arc::new(auth)),
        ..Options::default()
    })
    .await;
    let admin = login(fx.addr, "root", "rootpw").await;

    let started = as_session(
        fx.addr,
        reqwest::Method::POST,
        "/api/v1/settings/github/connect",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(started.status(), 202);
    let started: serde_json::Value = started.json().await.unwrap();
    assert_eq!(started["pending"]["user_code"], "ABCD-1234");
    assert!(
        started["pending"]["verification_url"]
            .as_str()
            .unwrap()
            .starts_with("https://")
    );

    // Only now let the background flow fail.
    release.notify_one();

    // Poll until the background flow lands (the stub fails fast; bound it).
    let mut error = None;
    for _ in 0..50 {
        let poll = as_session(
            fx.addr,
            reqwest::Method::GET,
            "/api/v1/settings/github",
            &admin,
        )
        .send()
        .await
        .unwrap();
        let poll: serde_json::Value = poll.json().await.unwrap();
        if poll["pending"].is_null() {
            error = poll["error"].as_str().map(str::to_string);
            break;
        }
        tokio::time::sleep(std::time::Duration::from_millis(50)).await;
    }
    let error = error.expect("the flow must end");
    assert!(error.contains("denied"), "{error}");

    // Once-reported: the next poll is plain disconnected, no sticky error.
    let again = as_session(
        fx.addr,
        reqwest::Method::GET,
        "/api/v1/settings/github",
        &admin,
    )
    .send()
    .await
    .unwrap();
    let again: serde_json::Value = again.json().await.unwrap();
    assert!(again["error"].is_null());
    assert_eq!(again["connected"], false);
}

/// The download IS the backup story: a zip whose entries reproduce the
/// domain's files byte for byte, fetched with plain cookie auth (an anchor
/// click), admin-only.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn the_archive_download_is_a_faithful_zip() {
    let fx = serve(Options::default()).await;
    let admin = login(fx.addr, "root", "rootpw").await;

    let resp = as_session(
        fx.addr,
        reqwest::Method::GET,
        "/api/v1/domains/eng/archive",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(resp.status(), 200);
    assert_eq!(resp.headers()["content-type"], "application/zip");
    assert!(
        resp.headers()["content-disposition"]
            .to_str()
            .unwrap()
            .contains("eng-archive.zip")
    );
    let bytes = resp.bytes().await.unwrap();

    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(bytes.as_ref())).unwrap();
    let mut names: Vec<String> = (0..archive.len())
        .map(|i| archive.by_index(i).unwrap().name().to_string())
        .collect();
    names.sort();
    assert_eq!(names, ["MANIFEST.md", "alpha.md"]);
    let mut alpha = String::new();
    std::io::Read::read_to_string(&mut archive.by_name("alpha.md").unwrap(), &mut alpha).unwrap();
    assert_eq!(alpha, ALPHA);

    // Editor and viewer are 403 on this GET.
    for (name, pw) in [("eddy", "eddypw"), ("vera", "verapw")] {
        let session = login(fx.addr, name, pw).await;
        let resp = as_session(
            fx.addr,
            reqwest::Method::GET,
            "/api/v1/domains/eng/archive",
            &session,
        )
        .send()
        .await
        .unwrap();
        assert_eq!(resp.status(), 403, "{name}");
    }

    // The UI downloads this with an anchor click, which carries the cookie and
    // no CSRF header at all: a safe method, so the guard exempts it.
    let anchor = client()
        .get(format!("http://{}/api/v1/domains/eng/archive", fx.addr))
        .header("cookie", format!("fluid_session={}", admin.0))
        .send()
        .await
        .unwrap();
    assert_eq!(anchor.status(), 200, "an anchor click sends no csrf header");

    // An unknown domain is an honest 404, not an empty archive.
    let ghost = as_session(
        fx.addr,
        reqwest::Method::GET,
        "/api/v1/domains/ghost/archive",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(ghost.status(), 404);
}

/// The archive download is exactly where a read-only mirror wants it: a pure
/// read, and the instance's backup story, so read_only serves it.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn read_only_still_serves_the_archive_download() {
    let ro = serve(Options {
        read_only: true,
        ..Options::default()
    })
    .await;
    let admin = login(ro.addr, "root", "rootpw").await;

    let resp = as_session(
        ro.addr,
        reqwest::Method::GET,
        "/api/v1/domains/eng/archive",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(resp.status(), 200, "the backup of a read-only mirror");
}

/// Build a zip in memory: entry names are arbitrary STRINGS here on purpose -
/// traversal and Windows-hostile names exist only inside these buffers and
/// are never written to any disk.
fn zip_of(entries: &[(&str, &str)]) -> Vec<u8> {
    use std::io::Write;
    let mut cursor = std::io::Cursor::new(Vec::new());
    {
        let mut writer = zip::ZipWriter::new(&mut cursor);
        for (name, content) in entries {
            writer
                .start_file(*name, zip::write::SimpleFileOptions::default())
                .unwrap();
            writer.write_all(content.as_bytes()).unwrap();
        }
        writer.finish().unwrap();
    }
    cursor.into_inner()
}

/// An archive whose headers LIE about the uncompressed size: an honest zip of
/// a highly compressible 4 MiB entry, then every LE u32 equal to the honest
/// size (local header and central directory both) patched down to 10. Should
/// the patch ever hit a coincidental match inside the compressed stream, the
/// corrupted deflate also answers 422, just with a different detail - the
/// detail assertion in the test is what pins the metering guard specifically.
fn lying_zip() -> Vec<u8> {
    let big = "a".repeat(4 * 1024 * 1024);
    let mut bytes = zip_of(&[("bomb.md", big.as_str())]);
    let honest = (big.len() as u32).to_le_bytes();
    let lie = 10u32.to_le_bytes();
    let mut at = 0;
    while at + 4 <= bytes.len() {
        if bytes[at..at + 4] == honest {
            bytes[at..at + 4].copy_from_slice(&lie);
            at += 4;
        } else {
            at += 1;
        }
    }
    bytes
}

async fn post_zip(
    addr: std::net::SocketAddr,
    path: &str,
    session: &(String, String),
    bytes: Vec<u8>,
) -> reqwest::Response {
    client()
        .post(format!("http://{addr}{path}"))
        .header("cookie", format!("fluid_session={}", session.0))
        .header("x-csrf-token", &session.1)
        .header("content-type", "application/zip")
        .body(bytes)
        .send()
        .await
        .unwrap()
}

/// Spec section 10's archive bullet: export then import into an empty domain
/// reproduces the files; the preview names every entry's fate first (the
/// archive's own MANIFEST reported as ignored) and writes nothing.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn the_archive_round_trip_reproduces_the_files() {
    let fx = serve(Options::default()).await;
    let admin = login(fx.addr, "root", "rootpw").await;

    let exported = as_session(
        fx.addr,
        reqwest::Method::GET,
        "/api/v1/domains/eng/archive",
        &admin,
    )
    .send()
    .await
    .unwrap()
    .bytes()
    .await
    .unwrap()
    .to_vec();

    let created = as_session(fx.addr, reqwest::Method::POST, "/api/v1/domains", &admin)
        .json(&serde_json::json!({"mode": "local", "name": "restore"}))
        .send()
        .await
        .unwrap();
    assert_eq!(created.status(), 201);
    let created: serde_json::Value = created.json().await.unwrap();
    let restore_root = std::path::PathBuf::from(created["root"].as_str().unwrap());

    let preview = post_zip(
        fx.addr,
        "/api/v1/domains/restore/archive/preview",
        &admin,
        exported.clone(),
    )
    .await;
    assert_eq!(preview.status(), 200);
    let preview: serde_json::Value = preview.json().await.unwrap();
    let entry_status = |path: &str| -> String {
        preview["entries"]
            .as_array()
            .unwrap()
            .iter()
            .find(|e| e["path"] == path)
            .unwrap_or_else(|| panic!("no entry for {path}: {preview}"))["status"]
            .as_str()
            .unwrap()
            .to_string()
    };
    assert_eq!(entry_status("MANIFEST.md"), "ignored");
    assert_eq!(entry_status("alpha.md"), "new");
    assert_eq!(preview["dry_run"], true);
    assert_eq!(preview["new"], 1, "{preview}");
    assert_eq!(preview["ignored"], 1, "{preview}");
    // A preview is a dry run in the strict sense: no file landed.
    assert!(
        !restore_root.join("alpha.md").exists(),
        "the preview wrote nothing"
    );

    let done = post_zip(
        fx.addr,
        "/api/v1/domains/restore/archive/import",
        &admin,
        exported,
    )
    .await;
    assert_eq!(done.status(), 200);
    let done: serde_json::Value = done.json().await.unwrap();
    assert_eq!(done["written"], 1, "{done}");
    assert_eq!(done["dry_run"], false);

    // The file arrived byte for byte.
    let detail = as_session(
        fx.addr,
        reqwest::Method::GET,
        "/api/v1/domains/restore/engrams/alpha",
        &admin,
    )
    .send()
    .await
    .unwrap();
    assert_eq!(detail.status(), 200);
    let detail: serde_json::Value = detail.json().await.unwrap();
    assert_eq!(detail["content"].as_str().unwrap(), ALPHA);
}

/// Upload hygiene: zip-slip refuses the WHOLE archive (both separators and
/// the drive-colon shape), garbage bytes are 422, the entry-count cap holds,
/// and only .md entries are considered.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn hostile_and_oversized_archives_are_refused() {
    let fx = serve(Options::default()).await;
    let admin = login(fx.addr, "root", "rootpw").await;
    let preview_path = "/api/v1/domains/eng/archive/preview";

    for evil in [
        zip_of(&[("../escape.md", "x")]),
        zip_of(&[("a/../../escape.md", "x")]),
        zip_of(&[("back\\slash.md", "x")]),
        zip_of(&[("c:colon.md", "x")]),
        zip_of(&[("/absolute.md", "x")]),
    ] {
        let resp = post_zip(fx.addr, preview_path, &admin, evil).await;
        assert_eq!(
            resp.status(),
            422,
            "traversal shapes refuse the archive whole"
        );
    }
    // Nothing landed.
    assert!(!fx._tmp.path().join("escape.md").exists());

    let garbage = post_zip(fx.addr, preview_path, &admin, b"not a zip".to_vec()).await;
    assert_eq!(garbage.status(), 422);

    // A LYING header: declared sizes patched tiny while the stream inflates to
    // 4 MiB. The declared-size gate passes; only actual-byte metering catches
    // it (zip's readers do not cap output at the declared size).
    let resp = post_zip(fx.addr, preview_path, &admin, lying_zip()).await;
    assert_eq!(resp.status(), 422);
    let problem: serde_json::Value = resp.json().await.unwrap();
    assert!(
        problem["detail"]
            .as_str()
            .unwrap()
            .contains("decompresses past"),
        "the metering guard must be the one that fired: {problem}"
    );

    let mut too_many: Vec<(String, String)> = Vec::new();
    for i in 0..1001 {
        too_many.push((format!("e{i}.md"), "x".to_string()));
    }
    let refs: Vec<(&str, &str)> = too_many
        .iter()
        .map(|(a, b)| (a.as_str(), b.as_str()))
        .collect();
    let resp = post_zip(fx.addr, preview_path, &admin, zip_of(&refs)).await;
    assert_eq!(resp.status(), 422, "the entry-count cap");

    // The whole-archive total, which no single entry can reach: 33 entries of
    // exactly 1 MiB each pass the per-entry cap one by one and cross the 32
    // MiB total on the last one. Repeated bytes deflate to about a kilobyte
    // apiece, so the body is a few tens of KB against a 10 MiB limit - the
    // guard is reachable from inside this surface's own bounds.
    let one_mib = "a".repeat(1024 * 1024);
    let names: Vec<String> = (0..33).map(|i| format!("big{i}.md")).collect();
    let big: Vec<(&str, &str)> = names
        .iter()
        .map(|name| (name.as_str(), one_mib.as_str()))
        .collect();
    let resp = post_zip(fx.addr, preview_path, &admin, zip_of(&big)).await;
    assert_eq!(resp.status(), 422);
    let problem: serde_json::Value = resp.json().await.unwrap();
    assert!(
        problem["detail"].as_str().unwrap().contains("total limit"),
        "the total cap must be the one that fired: {problem}"
    );

    let mixed = zip_of(&[("readme.txt", "not markdown"), ("ok.md", ALPHA)]);
    let resp = post_zip(fx.addr, preview_path, &admin, mixed).await;
    let report: serde_json::Value = resp.json().await.unwrap();
    let txt = report["entries"]
        .as_array()
        .unwrap()
        .iter()
        .find(|e| e["path"] == "readme.txt")
        .unwrap();
    assert_eq!(txt["status"], "ignored");
}

/// The collision policies: a second import skips everything, overwrite
/// replaces content, and an invalid entry (hard verify errors) is never
/// written under either policy. A MANIFEST is screened whatever its spelling.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn collision_policies_and_invalid_entries_hold() {
    let fx = serve(Options::default()).await;
    let admin = login(fx.addr, "root", "rootpw").await;
    let import_path = "/api/v1/domains/eng/archive/import";

    let edited = ALPHA.replace("A rule about alpha.", "An imported, sharper rule.");
    let archive = zip_of(&[("alpha.md", edited.as_str())]);

    let skip = post_zip(fx.addr, import_path, &admin, archive.clone()).await;
    let skip: serde_json::Value = skip.json().await.unwrap();
    assert_eq!(skip["skipped"], 1, "skip is the default policy: {skip}");

    let over = post_zip(
        fx.addr,
        &format!("{import_path}?policy=overwrite"),
        &admin,
        archive,
    )
    .await;
    let over: serde_json::Value = over.json().await.unwrap();
    assert_eq!(over["written"], 1, "{over}");
    let on_disk = std::fs::read_to_string(fx._tmp.path().join("eng/alpha.md")).unwrap();
    assert!(on_disk.contains("sharper"));

    let bad_policy = post_zip(
        fx.addr,
        &format!("{import_path}?policy=merge"),
        &admin,
        zip_of(&[("x.md", "y")]),
    )
    .await;
    assert_eq!(bad_policy.status(), 422);
    let problem: serde_json::Value = bad_policy.json().await.unwrap();
    let detail = problem["detail"].as_str().unwrap();
    assert!(
        detail.contains("skip") && detail.contains("overwrite"),
        "the refusal names the two policies there are: {problem}"
    );

    // A MANIFEST is screened by NAME, not by spelling: the filesystem under a
    // domain is case-insensitive on macOS and Windows, so a `manifest.md`
    // entry would land on the domain's real MANIFEST.md - the one file a
    // domain cannot regenerate. Committed under overwrite, the policy that
    // would do the damage.
    let manifest_before = std::fs::read_to_string(fx._tmp.path().join("eng/MANIFEST.md")).unwrap();
    let manifests = zip_of(&[("manifest.md", ALPHA), ("sub/Manifest.md", ALPHA)]);
    let resp = post_zip(
        fx.addr,
        &format!("{import_path}?policy=overwrite"),
        &admin,
        manifests,
    )
    .await;
    let report: serde_json::Value = resp.json().await.unwrap();
    assert_eq!(report["ignored"], 2, "{report}");
    assert_eq!(report["written"], 0, "{report}");
    assert_eq!(
        std::fs::read_to_string(fx._tmp.path().join("eng/MANIFEST.md")).unwrap(),
        manifest_before,
        "the domain keeps its own MANIFEST"
    );
    assert!(!fx._tmp.path().join("eng/sub/Manifest.md").exists());

    // Unparseable frontmatter = hard error = invalid, withheld from the engine
    // even under overwrite, with findings attached.
    let broken = zip_of(&[("broken.md", "---\ntitle: [unclosed\n---\nbody")]);
    let resp = post_zip(
        fx.addr,
        &format!("{import_path}?policy=overwrite"),
        &admin,
        broken,
    )
    .await;
    let report: serde_json::Value = resp.json().await.unwrap();
    let entry = &report["entries"].as_array().unwrap()[0];
    assert_eq!(entry["status"], "invalid", "{report}");
    assert!(!fx._tmp.path().join("eng/broken.md").exists());
}

/// The OKF reserved names are screened by NAME, not by spelling, at the layer
/// that faces an uploaded zip.
///
/// `log.md` is the sharp case. It is reserved but never generated, so what a
/// domain holds there is user content nothing brings back - and on a
/// case-insensitive filesystem (APFS, NTFS) an entry called `Log.md` addresses
/// the existing `log.md`: the write renames onto it and replaces its bytes
/// while the on-disk name stays lowercase. Run under `policy=overwrite`, the
/// policy that would do the damage.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn reserved_names_are_ignored_whatever_their_case() {
    let fx = serve(Options::default()).await;
    let admin = login(fx.addr, "root", "rootpw").await;
    let archive = zip_of(&[
        ("index.md", ALPHA),
        ("log.md", ALPHA),
        ("Log.md", ALPHA),
        ("sub/Index.md", ALPHA),
    ]);

    // The preview names all four as ignored before anything is committed - the
    // precedence the screen exists for: ignored ahead of any verify verdict.
    let preview = post_zip(
        fx.addr,
        "/api/v1/domains/eng/archive/preview",
        &admin,
        archive.clone(),
    )
    .await;
    assert_eq!(preview.status(), 200);
    let preview: serde_json::Value = preview.json().await.unwrap();
    assert_eq!(preview["ignored"], 4, "{preview}");
    assert_eq!(preview["new"], 0, "{preview}");
    for entry in preview["entries"].as_array().unwrap() {
        assert_eq!(entry["status"], "ignored", "{entry}");
        // The outer screen's own wording. Asserted because the engine screens
        // these again: without this, a REST-layer regression would be covered
        // by the inner defense and the test would still pass.
        assert!(
            entry["reason"]
                .as_str()
                .unwrap()
                .contains("reserved OKF names"),
            "the REST screen must be the one that answered: {entry}"
        );
    }

    let done = post_zip(
        fx.addr,
        "/api/v1/domains/eng/archive/import?policy=overwrite",
        &admin,
        archive,
    )
    .await;
    assert_eq!(done.status(), 200);
    let done: serde_json::Value = done.json().await.unwrap();
    assert_eq!(done["ignored"], 4, "{done}");
    assert_eq!(done["written"], 0, "{done}");
    assert_eq!(
        std::fs::read_to_string(fx._tmp.path().join("eng/log.md")).unwrap(),
        LOG,
        "the domain's log is untouched, whatever case the archive spelled it in"
    );
    assert!(
        !fx._tmp.path().join("eng/sub").exists(),
        "a nested reserved name creates no folder either"
    );
}

/// Task 6 (0.13.0 close-out): the domain must be resolved before the upload
/// is decompressed, so a request that can never succeed does not pay for the
/// decompression first.
///
/// The order-proving case is bytes that are NOT a zip at all, aimed at a
/// domain that does not exist: today `read_archive` runs first and answers
/// 422 for the bad bytes without ever looking at the domain, so this exact
/// case is the red proof of the reorder, not merely a 404 that would also
/// pass today. A plain leg follows it: a genuinely valid small archive
/// against the same unregistered domain, which already answers 404 today
/// (`import_domain_files` resolves the domain on its own path) and must go
/// on doing so - it is the control that shows the fix changed WHERE the 404
/// comes from, not whether one arrives at all.
///
/// Decision 19: the resolve has to land BELOW `identity.require_admin()` and
/// `refuse_read_only`, never above them, or a read-only instance starts
/// answering 404 where it answers 403 and a non-admin caller learns which
/// domains exist. Both are pinned here by comparing a known domain (`eng`)
/// against an unknown one (`ghost`): a read-only admin and a non-admin editor
/// must see the identical 403 for both, never a 404 that would tell them
/// `ghost` is the one that is missing.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn preview_resolves_the_domain_before_it_decompresses() {
    let fx = serve(Options::default()).await;
    let admin = login(fx.addr, "root", "rootpw").await;
    let ghost_path = "/api/v1/domains/ghost/archive/preview";

    let resp = post_zip(fx.addr, ghost_path, &admin, b"not a zip".to_vec()).await;
    assert_eq!(
        resp.status(),
        404,
        "the domain must be resolved before the bytes are ever read as a zip"
    );
    let problem: serde_json::Value = resp.json().await.unwrap();
    assert!(
        problem["detail"].as_str().unwrap().contains("ghost"),
        "the 404 must name the missing domain: {problem}"
    );

    let resp = post_zip(fx.addr, ghost_path, &admin, zip_of(&[("a.md", ALPHA)])).await;
    assert_eq!(
        resp.status(),
        404,
        "a genuinely valid archive against the same unknown domain is still 404"
    );

    // Decision 19, direction one: read-only refuses before the domain is
    // looked up, so it answers the same 403 whether the domain exists or not.
    let ro = serve(Options {
        read_only: true,
        ..Options::default()
    })
    .await;
    let ro_admin = login(ro.addr, "root", "rootpw").await;
    let known = post_zip(
        ro.addr,
        "/api/v1/domains/eng/archive/preview",
        &ro_admin,
        b"not a zip".to_vec(),
    )
    .await;
    let unknown = post_zip(ro.addr, ghost_path, &ro_admin, b"not a zip".to_vec()).await;
    assert_eq!(known.status(), 403, "read-only refuses a known domain too");
    assert_eq!(
        unknown.status(),
        403,
        "read-only must not answer 404 for an unknown domain"
    );
    assert_eq!(
        known.status(),
        unknown.status(),
        "read-only must look identical whether the domain exists or not"
    );

    // Decision 19, direction two: a non-admin is refused before the domain is
    // looked up, so an editor cannot tell an unknown domain from one they
    // simply may not touch.
    let editor = login(fx.addr, "eddy", "eddypw").await;
    let known = post_zip(
        fx.addr,
        "/api/v1/domains/eng/archive/preview",
        &editor,
        b"not a zip".to_vec(),
    )
    .await;
    let unknown = post_zip(fx.addr, ghost_path, &editor, b"not a zip".to_vec()).await;
    assert_eq!(
        known.status(),
        403,
        "a non-admin is refused a known domain too"
    );
    assert_eq!(
        unknown.status(),
        403,
        "a non-admin must not learn that an unknown domain does not exist"
    );
    assert_eq!(
        known.status(),
        unknown.status(),
        "a non-admin must see the same answer whether the domain exists or not"
    );
}

/// The import twin of `preview_resolves_the_domain_before_it_decompresses`;
/// see that test's doc for the full reasoning. Kept as its own test because
/// `import` is a distinct handler with its own admin, read-only and policy
/// checks ahead of the shared `run_archive`, and the order pinned here is
/// what stops a future edit from hoisting the resolve above them on the
/// import side while leaving preview alone.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn import_resolves_the_domain_before_it_decompresses() {
    let fx = serve(Options::default()).await;
    let admin = login(fx.addr, "root", "rootpw").await;
    let ghost_path = "/api/v1/domains/ghost/archive/import";

    let resp = post_zip(fx.addr, ghost_path, &admin, b"not a zip".to_vec()).await;
    assert_eq!(
        resp.status(),
        404,
        "the domain must be resolved before the bytes are ever read as a zip"
    );
    let problem: serde_json::Value = resp.json().await.unwrap();
    assert!(
        problem["detail"].as_str().unwrap().contains("ghost"),
        "the 404 must name the missing domain: {problem}"
    );

    let resp = post_zip(fx.addr, ghost_path, &admin, zip_of(&[("a.md", ALPHA)])).await;
    assert_eq!(
        resp.status(),
        404,
        "a genuinely valid archive against the same unknown domain is still 404"
    );

    let ro = serve(Options {
        read_only: true,
        ..Options::default()
    })
    .await;
    let ro_admin = login(ro.addr, "root", "rootpw").await;
    let known = post_zip(
        ro.addr,
        "/api/v1/domains/eng/archive/import",
        &ro_admin,
        b"not a zip".to_vec(),
    )
    .await;
    let unknown = post_zip(ro.addr, ghost_path, &ro_admin, b"not a zip".to_vec()).await;
    assert_eq!(known.status(), 403, "read-only refuses a known domain too");
    assert_eq!(
        unknown.status(),
        403,
        "read-only must not answer 404 for an unknown domain"
    );
    assert_eq!(
        known.status(),
        unknown.status(),
        "read-only must look identical whether the domain exists or not"
    );

    let editor = login(fx.addr, "eddy", "eddypw").await;
    let known = post_zip(
        fx.addr,
        "/api/v1/domains/eng/archive/import",
        &editor,
        b"not a zip".to_vec(),
    )
    .await;
    let unknown = post_zip(fx.addr, ghost_path, &editor, b"not a zip".to_vec()).await;
    assert_eq!(
        known.status(),
        403,
        "a non-admin is refused a known domain too"
    );
    assert_eq!(
        unknown.status(),
        403,
        "a non-admin must not learn that an unknown domain does not exist"
    );
    assert_eq!(
        known.status(),
        unknown.status(),
        "a non-admin must see the same answer whether the domain exists or not"
    );
}
