/**
 * Names for the payload shapes the app passes around.
 *
 * `gen/` is generated by `pnpm generate:api`, and its flat names (`CreateBody`,
 * `IssueBody`) say little about which route they belong to. This file is the
 * readable half: one place that says which generated schema a screen means, so
 * a renamed schema is one edit here rather than a search across the app.
 * Nothing is redefined - every export is the generated type under the name the
 * app uses, so the OpenAPI document stays the single source.
 */

/** One account, as every route hands it back. Carries no password material. */
export type { User } from "./gen";

/** What an account may do: `viewer`, `editor` or `admin`. */
export type { Role } from "./gen";

/** The capability probe: who the caller is and what this instance allows. */
export type { MeResponse } from "./gen";

/** What a successful `POST /auth/login` answers with. */
export type { LoginResponse } from "./gen";

/** What `POST /auth/setup` takes: the first admin, and a setup token if one is needed. */
export type { SetupBody } from "./gen";

/** The RFC 9457 body every failure on this API carries. */
export type { ProblemDetail } from "./gen";

/** The `{"users": [...]}` envelope `GET /users` answers with. */
export type { UsersResponse } from "./gen";

/** The `{"user": ...}` envelope every user mutation answers with. */
export type { UserResponse } from "./gen";

/** What `POST /users` takes. */
export type { CreateBody as CreateUserBody } from "./gen";

/** What `PATCH /users/{name}` takes. */
export type { PatchBody as PatchUserBody } from "./gen";

/** What `POST /domains/{domain}/engrams` takes. */
export type { CreateEngramBody } from "./gen";

/** What `PUT /domains/{domain}/engrams/{permalink}` takes. */
export type { SaveEngramBody } from "./gen";

/** What `POST /domains/{domain}/retire` takes. */
export type { RetireBody } from "./gen";

/** What `POST /domains/{domain}/move` takes. */
export type { MoveBody } from "./gen";

/** What both verbs on `/domains/{domain}/evolve/ack` take. */
export type { AckBody } from "./gen";

/** What `PUT /domains/{domain}/manifest` takes. */
export type { SaveManifestBody } from "./gen";

/** What `GET /settings/github` and every GitHub settings verb answer with. */
export type { GithubStatusResponse } from "./gen";

/** What `GET /me/github-identity` and every identity verb answer with. */
export type { GithubIdentityResponse } from "./gen";

/** What an archive preview and an archive import both answer with. */
export type { ArchiveReport } from "./gen";

/**
 * What `POST /domains` takes.
 *
 * Named for the wire rather than for the caller, because `api/admin.ts`
 * exports a `CreateDomainBody` of its own: the screen's version narrows `mode`
 * to the three modes that exist and leaves out the nulls a JSON body may
 * carry, and it is checked against this one on its way out.
 */
export type { CreateDomainBody as CreateDomainWireBody } from "./gen";

/** What `POST /validate` takes. */
export type { ValidateBody } from "./gen";

/** One finding a validation raises. */
export type { ValidateFinding } from "./gen";

/** What `POST /validate` answers with. */
export type { ValidateResponse } from "./gen";

/**
 * One row of the caller's own MCP token list: label, when it was issued, when
 * it last resolved a request. Never the token itself - only its hash is
 * stored, so there is nothing to show back after issuance.
 */
export type { McpTokenInfo } from "./gen";

/** What `POST /me/mcp-tokens` takes. */
export type { IssueBody as IssueMcpTokenBody } from "./gen";

/**
 * What issuing or rotating an MCP token answers with: the secret, readable
 * here and nowhere else, ever.
 */
export type { IssuedTokenResponse as IssuedMcpToken } from "./gen";

/**
 * Which ways into this instance exist, for the sign-in screen to draw. Public:
 * it is read before anybody is signed in, and it carries the button's label
 * and no configuration beyond it.
 */
export type { ProvidersResponse } from "./gen";

/** What `POST /auth/oidc/login` answers with: where to navigate to link an identity. */
export type { StartLinkResponse } from "./gen";

/** The single sign-on provider's half of that: whether to draw it, and what to write on it. */
export type { OidcProviderView } from "./gen";

/**
 * One provider identity an account holds. The pair of issuer and subject is
 * the durable key; `linked_by` says who made it - `jit` for a link a first
 * sign-on created with its account, `cli` for one an administrator made,
 * otherwise the account that linked it to itself.
 */
export type { IdentityLink } from "./gen";

/** What `GET /me/identity-links` answers with: the links, and whether a password backs them up. */
export type { IdentityLinksResponse } from "./gen";

/** What `GET /domains/{domain}/members` answers with: who owns and is invited into a domain. */
export type { MembersResponse } from "./gen";

/** One membership row: who, at what level, added by whom and when. */
export type { DomainMember } from "./gen";

/** What a member may do on one private domain: `viewer`, `editor` or `manager`. */
export type { MemberLevel } from "./gen";

/** What `PUT /domains/{domain}/members/{principal}` takes. */
export type { MemberBody } from "./gen";

/** What `PUT /domains/{domain}/owner` takes. */
export type { OwnerBody } from "./gen";

/** What `PUT /domains/{domain}/visibility` takes. */
export type { VisibilityBody } from "./gen";

/** What `POST /domains/{domain}/rename` takes. */
export type { RenameBody as RenameWireBody } from "./gen";

/**
 * What the consent screen shows: the client name, the redirect host (with
 * the loopback marker), and the account that is about to grant it. Never the
 * protocol - no code, no challenge, no state, no client id.
 */
export type { AuthorizationView } from "./gen";

/** What deciding a pending authorization answers with: where to navigate next. */
export type { DecisionResponse } from "./gen";

/**
 * One row of an account's connected OAuth clients: which client, since when,
 * when it was last used, and until when its refresh token may keep rotating.
 * Never a token - only hashes are stored on the server, so there is nothing
 * to show back.
 */
export type { OauthGrantInfo } from "./gen";

/**
 * One draft handed over by its author: where it stands, whose it is, whether
 * this account may edit it, and the text itself. The single payload that
 * crosses between two actors' overlays.
 */
export type { AcceptedDraft } from "./gen";

/** A freshly minted share-link. Its token is readable in this reply and never again. */
export type { MintedLinkResponse } from "./gen";

/** One share-link standing on a draft: who redeemed it, and when it was made. */
export type { OverlayGrant } from "./gen";
