/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /activity` - what was recorded lately, newest first, which is what a
         *     client opens on.
         * @description The window defaults in the engine rather than here, so the API and the MCP
         *     tool answer the same question when neither is told which window to use.
         */
        get: operations["get_activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a session.
         * @description Sets the `fluid_session` cookie and returns the account plus the CSRF token every later mutating request must echo in `x-csrf-token`. Any session the request arrived holding is revoked first, so a planted token cannot survive a login.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the session and clear its cookie. Not an error without one: a browser
         *     logging out twice, or with a cookie this server has already forgotten, is
         *     ordinary. Guarded by the CSRF check like any other mutating request, so
         *     another origin cannot log a user out.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The capability probe a client calls before anything else: who it is, whether
         *     it is being served anonymously, whether this instance refuses content
         *     mutations, and which server version it is talking to, so a mismatched UI can
         *     say so instead of failing later.
         * @description Who the caller is, whether it is being served anonymously, whether this instance refuses content mutations, and which server version it is talking to. Also issues the CSRF token every later mutating request must echo in `x-csrf-token`: a cookie session has its token reissued here, and a trusted-header identity is minted a session on the first call, which is the only way that mode obtains a token.
         */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /context` - the graph around an anchor: the anchored engrams as seed
         *     nodes, the neighborhood ranked out from them, and the edges that connect what
         *     came back. This is what a client draws a relationship view from.
         * @description The three ways an anchor can be wrong stay distinguishable: absent is a 400
         *     from the extractor, one that is not a `crystalline://` URL is the engine's
         *     own 422, and one pointing at an engram nobody wrote is a 404.
         *
         *     `timeframe` is not exposed: the engine documents it as advisory in this
         *     version, and a parameter that does not change the answer is not worth a
         *     client learning.
         */
        get: operations["get_context"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /domains` - every registered domain with its counts, its kind and its
         *     routing bullets, plus the behavior rules that govern them.
         * @description `include_routing` is always on rather than a query parameter: a browser
         *     client is exactly the caller that has no other way to learn what a domain is
         *     for, and the bullets are a handful of lines per domain.
         */
        get: operations["list_domains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domain}/engrams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One domain's engrams, filtered by frontmatter and paged.
         * @description A filter-only search, so the answer carries the same page envelope a search does and a client pages it the same way. Listing by folder is not here: the tree endpoint owns the navigation view and this one owns the frontmatter view.
         *
         *     A domain nobody registered is a 404, while filters that match nothing are an empty page: two states a client can tell apart.
         */
        get: operations["list_engrams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domain}/engrams/{permalink}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One engram in full.
         * @description Its frontmatter, its markdown as written and the references the engine resolves around it.
         *
         *     The response carries an `ETag` over the markdown, so a client knows which version it is holding and can say so when it later writes back.
         */
        get: operations["get_engram"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domain}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /domains/{domain}/manifest` - the domain's MANIFEST markdown as
         *     written, so a client can render or edit the source rather than a reduction
         *     of it.
         */
        get: operations["get_domain_manifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domain}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /domains/{domain}/tree` - one domain's engrams and subfolders under a
         *     path, the navigation a file tree in the UI is built from.
         */
        get: operations["get_domain_tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /graph` - the nodes and typed edges around an anchor: every node with
         *     the address, title, status and type a client labels it with, every edge with
         *     its direction and `rel_type`, and `truncated` saying whether the node cap
         *     cut anything.
         * @description Both bounds are the server's to decide: the engine clamps the depth to one or
         *     two hops and the node count to its own ceiling, so a hand-written URL can ask
         *     neither for nothing nor for a whole index in one payload. A clamped request
         *     is answered rather than refused - the honest report of what was returned is
         *     the payload itself.
         *
         *     Retired engrams are part of the answer, carrying their status. The graph is
         *     the shape of what is written, and a client fades what is retired rather than
         *     being served a graph with the retired nodes already cut out of it.
         *
         *     The three ways an anchor can be wrong stay distinguishable, as on `/context`:
         *     absent is a 400 from the extractor, one that is not a `crystalline://` URL is
         *     the engine's own 422, and one pointing at an engram nobody wrote is a 404.
         */
        get: operations["get_graph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This API's own OpenAPI 3.1 document.
         * @description Served behind the viewer guard like every other data route: the description of a closed API is part of what being closed by default protects. Tooling does not need this route, since the document is a committed artifact in the repository at `crates/service/openapi/fluid-v1.json`.
         */
        get: operations["get_openapi_document"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /search` - search across the registered domains, or across the ones
         *     `domains` names.
         * @description The answer is the engine's page envelope (`mode`, `total`, `page`, `limit`,
         *     `count`, `hits`), so a client pages a search the way it pages a listing.
         *     `mode` is the mode that actually ran rather than the one asked for: hybrid
         *     and semantic fall back to text where there is nothing embedded to search, and
         *     the response says which happened rather than quietly answering from a
         *     different index than the caller expected.
         *
         *     A `search_type` the engine does not know is its own error, surfaced as a 422
         *     problem detail carrying the engine's message, so the caller learns which
         *     values do work instead of being handed a bare status.
         *
         *     `metadata_filters` is not exposed: it takes a JSON object of comparisons,
         *     which has no honest query-string spelling, and no client needs it yet.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every account, by name.
         * @description An account carries no password material, so the rows go out as they come back from the store. Admin only: the account list names every way into the instance and who holds it.
         */
        get: operations["list_users"];
        put?: never;
        /**
         * `POST /users` - add an account, answering 201 with the account as stored.
         * @description The response is read back out of the store rather than echoed from the
         *     request, so what the client renders is what was written: the folded name,
         *     the defaulted display name, and the disabled flag the row starts with.
         */
        post: operations["create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * `DELETE /users/{name}` - remove an account and every session it holds,
         *     answering 204.
         * @description An admin may not remove its own account (409), and the store refuses to
         *     remove the last enabled admin whoever asks (409 as well, in its own words).
         */
        delete: operations["delete_user"];
        options?: never;
        head?: never;
        /**
         * `PATCH /users/{name}` - change a role, a disabled flag, a password, or any
         *     combination, answering with the account as it now stands.
         * @description Two of the three fields are revocations as well as edits: setting a password
         *     and disabling an account each delete every session that account holds, in
         *     the store and in the same transaction as the change. That is what makes this
         *     route useful against a compromised account - a reset that left the intruder's
         *     cookie alive for the rest of its 30-day life would be theatre - and it means
         *     an admin resetting their own password signs their own other sessions out too,
         *     this one included.
         *
         *     Every check runs before the first write, so a request that will be refused
         *     changes nothing. The writes themselves are one store call each rather than
         *     one transaction: the store's guarded statements each own their own
         *     invariant, and a failure part-way leaves the earlier fields applied and says
         *     which operation was refused. That is visible to a client only in the
         *     pathological case of a concurrent edit racing this one, since the refusals a
         *     caller can provoke on purpose - the last-admin guard and an unknown account
         *     - are decided identically by all three statements.
         */
        patch: operations["update_user"];
        trace?: never;
    };
    "/api/v1/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /vocabulary` - the words the domains are written in: the tags in use
         *     with their counts, the observation categories and the relation types, plus
         *     the near-duplicate clusters and tag aliases the engine reports when there are
         *     any.
         * @description The domain is a filter here rather than a path segment, so an unknown name
         *     answers an empty vocabulary rather than a 404: this route asks what is in
         *     use, and the answer to that can legitimately be nothing.
         */
        get: operations["get_vocabulary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A new account. `display` defaults to `name` as typed, and `email` is optional and never used for login. */
        CreateBody: {
            /**
             * @description Human-readable name for the UI. Defaults to `name` as typed.
             * @example Bob
             */
            display?: string | null;
            /**
             * @description Optional contact address.
             * @example bob@example.com
             */
            email?: string | null;
            /**
             * @description The login name, in any casing: the store folds it.
             * @example bob
             */
            name: string;
            /**
             * @description The initial password. Never stored in the clear; the store hashes it.
             * @example correct horse battery staple
             */
            password: string;
            /** @description What the new account may do. */
            role: components["schemas"]["Role"];
        };
        /** @description What `POST /auth/login` takes. */
        LoginBody: {
            /**
             * @description The account name, in any casing: the store folds it.
             * @example ada
             */
            name: string;
            /**
             * @description The password, checked with argon2id.
             * @example correct horse battery staple
             */
            password: string;
        };
        /**
         * @description What `POST /auth/login` answers with.
         *
         *     A type rather than an inline `json!`, so the OpenAPI document and the
         *     response are one definition. Same for the two below it.
         */
        LoginResponse: {
            /**
             * @description The session's CSRF token, which every later mutating request must echo
             *     in the `x-csrf-token` header (see `CSRF_HEADER`).
             *
             *     The header is named in plain backticks rather than through an intra-doc
             *     link because utoipa copies this comment into the published document,
             *     where a Rust link target reads as noise. Same wherever else a schema
             *     field's comment names something in this crate.
             * @example 9f2c1d7e4b6a8035
             */
            csrf: string;
            /** @description The account that was signed in. */
            user: components["schemas"]["User"];
        };
        /**
         * @description What `POST /auth/logout` answers with: an acknowledgement and nothing else,
         *     since a logout that found no session is a success too.
         */
        LogoutResponse: {
            /** @description Always true. */
            ok: boolean;
        };
        /**
         * @description What `GET /auth/me` answers with: everything a client needs before it draws
         *     anything.
         */
        MeResponse: {
            /** @description Whether the request is being served as the anonymous viewer. */
            anonymous: boolean;
            /**
             * @description The CSRF token of the session this request arrived on, or null when it
             *     arrived on no session.
             *
             *     Reissued here, not only by login, because the session cookie is
             *     `HttpOnly` and the token is not stored anywhere a reload survives: a
             *     browser that refreshes holds a live session whose token it can no longer
             *     produce, and would be unable to log out or to write until it logged in
             *     again. This probe is what a client opens on, so it is where the token
             *     belongs.
             *
             *     Null only for the anonymous viewer, which has no account and can never
             *     write; trusted-header identities are minted a session here on first
             *     call, so every identity that can mutate anything carries a token. See
             *     the `check_csrf` rule.
             *
             *     Handing the token back on a `GET` is safe for the same reason handing it
             *     back from login is: no CORS layer exists on this surface, so another
             *     origin can send the request but cannot read the answer. **That is load
             *     bearing - a CORS layer must not be added without revisiting this.**
             * @example 9f2c1d7e4b6a8035
             */
            csrf?: string | null;
            /** @description Whether this instance refuses content mutations. */
            read_only: boolean;
            user?: null | components["schemas"]["User"];
            /**
             * @description The server version, so a mismatched UI can say so.
             * @example 0.12.0
             */
            version: string;
        };
        /** @description Whichever of the three an admin wants to change. All absent is refused with a 422 rather than served as a no-op, so a client sending the wrong field names hears about it. */
        PatchBody: {
            /**
             * @description Whether the account is disabled. Disabling deletes every session the
             *     account holds, so it is a revocation rather than a flag a later
             *     re-enabling hands back; it also stops any new login.
             */
            disabled?: boolean | null;
            /**
             * @description A replacement password. Setting it revokes every session the account
             *     holds, so whoever was signed in under the old one is signed out.
             */
            password?: string | null;
            role?: null | components["schemas"]["Role"];
        };
        /** @description An RFC 9457 problem detail, sent as `application/problem+json`. Every failure on this surface has this shape, so a client can branch on `status` alone. */
        ProblemDetail: {
            /**
             * @description The specific occurrence, safe to show to the caller.
             * @example no engram 'ghost' in domain 'eng'
             */
            detail: string;
            /**
             * Format: int32
             * @description The HTTP status, mirrored into the body so a client that only has the
             *     parsed payload can still branch on it.
             * @example 404
             */
            status: number;
            /**
             * @description A short, stable, human-readable summary of the problem type.
             * @example not found
             */
            title: string;
            /**
             * @description The problem type URI. Always `about:blank`: `status` and `title` carry
             *     the classification, and this surface publishes no per-problem pages to
             *     point at.
             * @example about:blank
             */
            type: string;
        };
        /**
         * @description What a user may do. Ordered least to most privileged; the REST layer maps
         *     each endpoint to the minimum role it accepts.
         * @enum {string}
         */
        Role: "viewer" | "editor" | "admin";
        /**
         * @description One account. Carries no password material, so it is safe to hand to a
         *     handler and serialize into a response.
         */
        User: {
            /**
             * @description A disabled account keeps its rows but can neither log in nor use an
             *     already-issued session.
             */
            disabled: boolean;
            /**
             * @description Human-readable name for the UI.
             * @example Ada Lovelace
             */
            display: string;
            /**
             * @description Optional contact address; never used for login.
             * @example ada@example.com
             */
            email?: string | null;
            /**
             * @description When this account last resolved a session or arrived through the
             *     trusted header, RFC 3339. Null for an account never seen.
             * @example 2026-08-08T09:14:22Z
             */
            last_seen?: string | null;
            /**
             * @description The login name and primary key. Also the identity the trusted-header
             *     mode provisions against.
             * @example ada
             */
            name: string;
            /** @description What this account may do. */
            role: components["schemas"]["Role"];
        };
        /**
         * @description What the two writing routes answer with: the account as stored, read back
         *     after the write rather than echoed from the request.
         */
        UserResponse: {
            /** @description The account as it now stands. */
            user: components["schemas"]["User"];
        };
        /**
         * @description What `GET /users` answers with. A wrapper rather than a bare array, matching
         *     the `{"users": [...]}` envelope `crystalline users list --json` prints.
         */
        UsersResponse: {
            /** @description Every account, by name. */
            users: components["schemas"]["User"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_activity: {
        parameters: {
            query?: {
                /**
                 * @description Restrict to these domains, comma separated. Defaults to every registered
                 *     domain.
                 * @example eng,ops
                 */
                domains?: string;
                /**
                 * @description A recency window such as `7d`, `24h` or `2w`. Defaults to `7d`.
                 * @example 7d
                 */
                timeframe?: string;
                /**
                 * @description Restrict to these `type` values, comma separated.
                 * @example decision,runbook
                 */
                types?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The engine's own activity payload, unchanged, with the window it actually used echoed back. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "count": 1,
                     *       "engrams": [
                     *         {
                     *           "domain": "eng",
                     *           "engram_type": "engram",
                     *           "permalink": "alpha",
                     *           "recorded_at": "2026-08-04",
                     *           "status": "stable",
                     *           "tags": [
                     *             "eng"
                     *           ],
                     *           "title": "Alpha"
                     *         }
                     *       ],
                     *       "timeframe": "7d"
                     *     }
                     */
                    "application/json": Record<string, never>;
                };
            };
            /** @description The query string will not parse. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Signed in. The session cookie is set and the CSRF token is in the body. */
            200: {
                headers: {
                    /** @description The `fluid_session` session cookie, HttpOnly and SameSite=Lax. */
                    "set-cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description The body is not JSON. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The name or password is wrong. One message for every way this can fail, so nothing is learned about which accounts exist. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The body is not `application/json`. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The body is JSON but not a login. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out, whether or not there was a session to revoke. */
            200: {
                headers: {
                    /** @description Clears the `fluid_session` cookie. */
                    "set-cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description The identity did not echo its CSRF token, or carries none yet and must call `/auth/me` first, or the trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Who the caller is and what this instance allows. Answered without an identity too, which is how a client learns it has to log in. */
            200: {
                headers: {
                    /** @description The `fluid_session` session cookie, HttpOnly and SameSite=Lax. Set only when this call mints a session, which is the first call from a trusted-header identity. */
                    "set-cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description The trusted-header identity names a disabled account. The guard resolves identity ahead of routing, so this answer reaches even the paths that are served without one. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_context: {
        parameters: {
            query: {
                /**
                 * @description A `crystalline://domain/permalink` anchor. A `/*` suffix globs a prefix.
                 * @example crystalline://eng/alpha
                 */
                anchor: string;
                /**
                 * @description Traversal depth, 1 to 3. Defaults to 1.
                 * @example 1
                 */
                depth?: number;
                /**
                 * @description Restrict the returned neighborhood to these domains, comma separated.
                 * @example eng,ops
                 */
                domains?: string;
                /**
                 * @description Maximum related engrams beyond the anchors. Defaults to 10.
                 * @example 10
                 */
                max_related?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The engine's own context payload, unchanged: the anchored engrams as seed nodes plus the neighborhood ranked out from them. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "anchor": "crystalline://eng/alpha",
                     *       "depth": 1,
                     *       "edges": [
                     *         {
                     *           "from": 1,
                     *           "kind": "relation",
                     *           "rel_type": "relates_to",
                     *           "to": 2
                     *         }
                     *       ],
                     *       "nodes": [
                     *         {
                     *           "domain": "eng",
                     *           "id": 1,
                     *           "permalink": "alpha",
                     *           "seed": true,
                     *           "title": "Alpha",
                     *           "type": "engram"
                     *         },
                     *         {
                     *           "domain": "eng",
                     *           "id": 2,
                     *           "permalink": "notes/beta",
                     *           "seed": false,
                     *           "title": "Beta",
                     *           "type": "engram"
                     *         }
                     *       ],
                     *       "timeframe": null
                     *     }
                     */
                    "application/json": Record<string, never>;
                };
            };
            /** @description The query string will not parse, `anchor` included: it has no default. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The anchor names no engram. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The anchor is not a `crystalline://` URL. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_domains: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The engine's own domain listing, unchanged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "behavior": [
                     *         "Search before answering from memory.",
                     *         "Record what was learned as an engram."
                     *       ],
                     *       "domains": [
                     *         {
                     *           "engrams": 4,
                     *           "kind": "file",
                     *           "last_sync": "2026-08-05T09:14:22Z",
                     *           "name": "eng",
                     *           "observations": 12,
                     *           "path": "/Users/ada/Documents/Crystalline/eng",
                     *           "relations": 3,
                     *           "when_to_use": [
                     *             "Route here for eng questions."
                     *           ]
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": Record<string, never>;
                };
            };
            /** @description No identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_engrams: {
        parameters: {
            query?: {
                /**
                 * @description Filter by `type`.
                 * @example decision
                 */
                type?: string;
                /**
                 * @description Filter by `status`.
                 * @example stable
                 */
                status?: string;
                /**
                 * @description Require all of these tags, comma separated. A URL is a string, so the
                 *     repeated-parameter form a `Vec` would need is not on offer here; the
                 *     list is split on the way in.
                 * @example eng,nested
                 */
                tags?: string;
                /**
                 * @description Only engrams recorded on or after this ISO date.
                 * @example 2026-01-31
                 */
                after?: string;
                /**
                 * @description One-based page number. Defaults to 1.
                 * @example 1
                 */
                page?: number;
                /**
                 * @description Page size. Defaults to 10.
                 * @example 10
                 */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description The registered domain. */
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The engine's page envelope, unchanged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "count": 1,
                     *       "hits": [
                     *         {
                     *           "domain": "eng",
                     *           "engram_type": "engram",
                     *           "kind": "engram",
                     *           "permalink": "alpha",
                     *           "score": 1,
                     *           "snippet": "The first engram in this domain.",
                     *           "status": "stable",
                     *           "tags": [
                     *             "eng"
                     *           ],
                     *           "title": "Alpha"
                     *         }
                     *       ],
                     *       "limit": 10,
                     *       "mode": "text",
                     *       "page": 1,
                     *       "total": 4
                     *     }
                     */
                    "application/json": Record<string, never>;
                };
            };
            /** @description The query string will not parse. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No such domain. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_engram: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The registered domain. */
                domain: string;
                /**
                 * @description The engram permalink. A permalink is a path, so this segment may contain slashes: `notes/deep/gamma`.
                 * @example notes/deep/gamma
                 */
                permalink: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The engine's own read payload, unchanged. */
            200: {
                headers: {
                    /** @description The quoted checksum of the engram as read, the same token a later write compares an `expected_checksum` against. */
                    etag?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "checksum": "3f8a1c05e2",
                     *       "content": "---\ntitle: Alpha\n---\n\nThe first engram.\n",
                     *       "domain": "eng",
                     *       "frontmatter": {
                     *         "permalink": "alpha",
                     *         "title": "Alpha"
                     *       },
                     *       "links": [],
                     *       "observations": [],
                     *       "path": "alpha.md",
                     *       "permalink": "alpha",
                     *       "relations": [],
                     *       "status": "stable",
                     *       "title": "Alpha",
                     *       "type": "engram",
                     *       "url": "crystalline://eng/alpha"
                     *     }
                     */
                    "application/json": Record<string, never>;
                };
            };
            /** @description No identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No such domain or engram. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_domain_manifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The registered domain. */
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The manifest source beside the domain it belongs to. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "domain": "eng",
                     *       "markdown": "---\ntitle: eng\n---\n\n## When to Use\n\n- Route here for eng questions.\n"
                     *     }
                     */
                    "application/json": Record<string, never>;
                };
            };
            /** @description No identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No such domain, or the domain carries no MANIFEST yet. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_domain_tree: {
        parameters: {
            query?: {
                /**
                 * @description A domain-relative folder path. Defaults to the root.
                 * @example notes
                 */
                path?: string;
                /**
                 * @description How many folder levels deep to list. Defaults to 1.
                 * @example 2
                 */
                depth?: number;
                /**
                 * @description A glob filtering the engram paths listed.
                 * @example notes/**
                 */
                glob?: string;
            };
            header?: never;
            path: {
                /** @description The registered domain. */
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The engine's own browse payload, unchanged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "domain": "eng",
                     *       "engrams": [
                     *         {
                     *           "path": "alpha.md",
                     *           "permalink": "alpha",
                     *           "status": "stable",
                     *           "title": "Alpha",
                     *           "type": "engram"
                     *         }
                     *       ],
                     *       "folders": [
                     *         "notes"
                     *       ],
                     *       "path": "/"
                     *     }
                     */
                    "application/json": Record<string, never>;
                };
            };
            /** @description The query string will not parse. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No such domain. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The glob is not a valid pattern. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_graph: {
        parameters: {
            query: {
                /**
                 * @description A `crystalline://domain/permalink` anchor. A `/*` suffix globs a prefix.
                 * @example crystalline://eng/alpha
                 */
                anchor: string;
                /**
                 * @description Traversal depth, 1 or 2. Defaults to 1.
                 * @example 1
                 */
                depth?: number;
                /**
                 * @description The most nodes to return. Defaults to 100, capped by the engine.
                 * @example 100
                 */
                max_nodes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The engine's own graph payload, unchanged: the flat node and edge lists a renderer draws from, with `truncated` saying whether the node cap cut anything. `id` is opaque and stable only within one response; the address is `crystalline://domain/permalink`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "edges": [
                     *         {
                     *           "from": 1,
                     *           "rel_type": "relates_to",
                     *           "to": 2
                     *         }
                     *       ],
                     *       "nodes": [
                     *         {
                     *           "domain": "eng",
                     *           "id": 1,
                     *           "permalink": "alpha",
                     *           "status": "stable",
                     *           "title": "Alpha",
                     *           "type": "engram"
                     *         },
                     *         {
                     *           "domain": "eng",
                     *           "id": 2,
                     *           "permalink": "notes/beta",
                     *           "status": "deprecated",
                     *           "title": "Beta",
                     *           "type": "engram"
                     *         }
                     *       ],
                     *       "truncated": false
                     *     }
                     */
                    "application/json": Record<string, never>;
                };
            };
            /** @description The query string will not parse, `anchor` included: it has no default. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The anchor names no engram. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The anchor is not a `crystalline://` URL. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_openapi_document: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This document. Behind the viewer guard like every other data route. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                /**
                 * @description The free-text query. Omit for a filter-only search.
                 * @example retrieval latency
                 */
                q?: string;
                /**
                 * @description Restrict to these domains, comma separated. Defaults to every registered
                 *     domain.
                 * @example eng,ops
                 */
                domains?: string;
                /**
                 * @description Filter by `type`.
                 * @example decision
                 */
                type?: string;
                /**
                 * @description Filter by `status`.
                 * @example stable
                 */
                status?: string;
                /**
                 * @description Require all of these tags, comma separated.
                 * @example eng,nested
                 */
                tags?: string;
                /**
                 * @description Only engrams recorded on or after this ISO date.
                 * @example 2026-01-31
                 */
                after?: string;
                /**
                 * @description hybrid (default), text, semantic, title or permalink.
                 * @example hybrid
                 */
                search_type?: string;
                /**
                 * @description Minimum cosine similarity for a semantic hit.
                 * @example 0.65
                 */
                min_similarity?: number;
                /**
                 * @description One-based page number. Defaults to 1.
                 * @example 1
                 */
                page?: number;
                /**
                 * @description Page size. Defaults to 10.
                 * @example 10
                 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The engine's page envelope, unchanged. `mode` is the mode that actually ran, which may be a fallback to text. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "count": 1,
                     *       "hits": [
                     *         {
                     *           "domain": "eng",
                     *           "engram_type": "engram",
                     *           "kind": "observation",
                     *           "line": 14,
                     *           "permalink": "alpha",
                     *           "score": 0.82,
                     *           "snippet": "...retrieval latency dropped by half...",
                     *           "status": "stable",
                     *           "tags": [
                     *             "eng"
                     *           ],
                     *           "title": "Alpha"
                     *         }
                     *       ],
                     *       "limit": 10,
                     *       "mode": "hybrid",
                     *       "page": 1,
                     *       "total": 3
                     *     }
                     */
                    "application/json": Record<string, never>;
                };
            };
            /** @description The query string will not parse. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description `search_type` names a mode the engine does not know. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsersResponse"];
                };
            };
            /** @description No identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not an admin, or the trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBody"];
            };
        };
        responses: {
            /** @description The account as stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description The body is not JSON. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not an admin, a cookie session did not echo its CSRF token, or the trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description That name is already taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The body is not `application/json`. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The body is JSON but not an account, or the password is empty. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The account, in any casing. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account and its sessions are gone. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not an admin, a cookie session did not echo its CSRF token, or the trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No such account. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The account is the caller's own, or is the last enabled admin. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    update_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The account, in any casing. */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchBody"];
            };
        };
        responses: {
            /** @description The account as it now stands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description The body is not JSON. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The caller is not an admin, a cookie session did not echo its CSRF token, or the trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No such account. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The change would disable the caller's own account, or would leave the installation without an enabled admin. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The body is not `application/json`. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The body changes nothing, or the new password is empty. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_vocabulary: {
        parameters: {
            query?: {
                /**
                 * @description Restrict to one domain. Omit for a vocabulary across every domain.
                 * @example eng
                 */
                domain?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The engine's own vocabulary payload, unchanged. `clusters` and `aliases` are omitted when there are none. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "aliases": [
                     *         {
                     *           "alias": "engineering",
                     *           "canonical": "eng"
                     *         }
                     *       ],
                     *       "categories": [
                     *         {
                     *           "count": 4,
                     *           "name": "decision"
                     *         }
                     *       ],
                     *       "domain": "eng",
                     *       "relation_types": [
                     *         {
                     *           "count": 2,
                     *           "name": "relates_to"
                     *         }
                     *       ],
                     *       "tags": [
                     *         {
                     *           "engrams": 3,
                     *           "name": "eng",
                     *           "observations": 5
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": Record<string, never>;
                };
            };
            /** @description The query string will not parse. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No identity. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The trusted-header identity names a disabled account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
