#![allow(dead_code)] // TODO(task 3): remove once install.rs consumes the receipt
//! The install receipt: `crystalline install`'s memory of what it wired up,
//! read back by later runs and by the session-start auto-reconcile to decide
//! which skills to update or retire and which install options to replay.
//!
//! One JSON file at `<state_dir>/installs.json` holds one record per install
//! target, keyed by harness, scope and (for project scope) the absolute
//! project path. The receipt is disposable derived state in the same spirit
//! as the search index: a corrupt file is regenerated by the next `install`,
//! and the reconcile logic in `install.rs` falls back to
//! overwrite-with-backup when no receipt is available, so losing the receipt
//! never loses user content.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crystalline_core::config;

/// The receipt format this binary writes. Bumped only on an incompatible
/// shape change; a reader skips a file carrying an unknown format rather
/// than guessing at its meaning.
const FORMAT: u32 = 1;

/// The whole receipt file: every install this machine's crystalline has
/// performed and not since uninstalled.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct Receipt {
    /// Format marker, [`FORMAT`] today.
    pub(crate) format: u32,
    /// One record per install target.
    #[serde(default)]
    pub(crate) installs: Vec<InstallRecord>,
}

impl Default for Receipt {
    fn default() -> Receipt {
        Receipt {
            format: FORMAT,
            installs: Vec::new(),
        }
    }
}

/// One install target's record: which harness and scope, which binary
/// version last reconciled it, which parts that install covered and the
/// exact content hash of every skill as written. The hashes are what let a
/// later version tell "old but untouched" from "user-edited".
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct InstallRecord {
    /// The harness id, `"claude-code"` or `"codex"` (the same spelling
    /// `HarnessKind::id` produces).
    pub(crate) harness: String,
    /// `"user"` or `"project"`.
    pub(crate) scope: String,
    /// The canonicalized project directory for a `--project` install; `None`
    /// at user scope. Part of the entry's identity: the same repository
    /// cloned twice is two installs.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) project_path: Option<String>,
    /// The `CARGO_PKG_VERSION` of the binary that last reconciled this
    /// target. The session-start auto-reconcile triggers on any difference
    /// from the running binary, downgrades included.
    pub(crate) version: String,
    /// Which parts this target has ever had installed (skip flags inverted,
    /// OR-merged across runs, since skipping means "do not touch", not
    /// "undo").
    pub(crate) parts: Parts,
    /// Every skill written, with its content hash as written.
    #[serde(default)]
    pub(crate) skills: Vec<RecordedSkill>,
}

/// The three installable parts of a harness setup.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub(crate) struct Parts {
    pub(crate) mcp: bool,
    pub(crate) hooks: bool,
    pub(crate) skills: bool,
}

/// One installed skill's name and content fingerprint.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct RecordedSkill {
    pub(crate) name: String,
    pub(crate) sha256: String,
}

impl InstallRecord {
    /// Whether this record is the one for a harness, scope and project path.
    fn matches(&self, harness: &str, scope: &str, project_path: Option<&str>) -> bool {
        self.harness == harness
            && self.scope == scope
            && self.project_path.as_deref() == project_path
    }
}

impl Receipt {
    /// The record for one install target, when it exists.
    pub(crate) fn find(
        &self,
        harness: &str,
        scope: &str,
        project_path: Option<&str>,
    ) -> Option<&InstallRecord> {
        self.installs
            .iter()
            .find(|r| r.matches(harness, scope, project_path))
    }

    /// Insert or replace the record for `record`'s own target key.
    pub(crate) fn upsert(&mut self, record: InstallRecord) {
        match self.installs.iter_mut().find(|r| {
            r.matches(
                &record.harness,
                &record.scope,
                record.project_path.as_deref(),
            )
        }) {
            Some(existing) => *existing = record,
            None => self.installs.push(record),
        }
    }

    /// Drop the record for one install target, reporting whether one was
    /// there to drop.
    pub(crate) fn remove(
        &mut self,
        harness: &str,
        scope: &str,
        project_path: Option<&str>,
    ) -> bool {
        let before = self.installs.len();
        self.installs
            .retain(|r| !r.matches(harness, scope, project_path));
        self.installs.len() != before
    }
}

/// The receipt's fixed location, `<state_dir>/installs.json`.
pub(crate) fn receipt_path() -> anyhow::Result<PathBuf> {
    Ok(config::state_dir()?.join("installs.json"))
}

/// Load the receipt. A missing file is the empty receipt (nothing installed
/// yet); an unreadable, unparseable or unknown-format file is an error the
/// caller decides how to survive: `install` regenerates from empty, the
/// session-start auto-reconcile skips quietly.
pub(crate) fn load(path: &Path) -> anyhow::Result<Receipt> {
    let bytes = match std::fs::read(path) {
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Receipt::default()),
        Err(e) => return Err(anyhow::anyhow!("could not read {}: {e}", path.display())),
        Ok(bytes) => bytes,
    };
    let receipt: Receipt = serde_json::from_slice(&bytes)
        .map_err(|e| anyhow::anyhow!("{} is not a valid install receipt: {e}", path.display()))?;
    if receipt.format != FORMAT {
        return Err(anyhow::anyhow!(
            "{} carries unknown receipt format {}",
            path.display(),
            receipt.format
        ));
    }
    Ok(receipt)
}

/// Write the receipt atomically, pretty-printed with a trailing newline,
/// matching how install writes harness settings files.
pub(crate) fn save(path: &Path, receipt: &Receipt) -> anyhow::Result<()> {
    let mut text = serde_json::to_string_pretty(receipt)?;
    text.push('\n');
    config::save_bytes(path, text.as_bytes())?;
    Ok(())
}

/// Lowercase hex sha256 of raw bytes: the fingerprint recorded per skill.
pub(crate) fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let digest = hasher.finalize();
    let mut s = String::with_capacity(digest.len() * 2);
    for b in digest {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn record(harness: &str, scope: &str, project_path: Option<&str>) -> InstallRecord {
        InstallRecord {
            harness: harness.to_string(),
            scope: scope.to_string(),
            project_path: project_path.map(String::from),
            version: "0.4.0".to_string(),
            parts: Parts {
                mcp: true,
                hooks: true,
                skills: true,
            },
            skills: vec![RecordedSkill {
                name: "crystalline-routing".to_string(),
                sha256: sha256_hex(b"body"),
            }],
        }
    }

    #[test]
    fn a_missing_file_loads_as_the_empty_receipt() {
        let dir = tempfile::tempdir().unwrap();
        let receipt = load(&dir.path().join("missing.json")).unwrap();
        assert_eq!(receipt.format, 1);
        assert!(receipt.installs.is_empty());
    }

    #[test]
    fn save_and_load_round_trip() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("installs.json");
        let mut receipt = Receipt::default();
        receipt.upsert(record("claude-code", "user", None));
        save(&path, &receipt).unwrap();
        let loaded = load(&path).unwrap();
        assert_eq!(loaded.installs.len(), 1);
        let entry = loaded.find("claude-code", "user", None).unwrap();
        assert_eq!(entry.version, "0.4.0");
        assert_eq!(entry.skills[0].name, "crystalline-routing");
        assert_eq!(entry.skills[0].sha256, sha256_hex(b"body"));
        // The file ends with a newline and is pretty-printed.
        let text = std::fs::read_to_string(&path).unwrap();
        assert!(text.ends_with('\n'));
        assert!(text.contains("\n  "));
    }

    #[test]
    fn corrupt_json_and_unknown_format_are_errors() {
        let dir = tempfile::tempdir().unwrap();
        let corrupt = dir.path().join("corrupt.json");
        std::fs::write(&corrupt, "{ nope").unwrap();
        assert!(load(&corrupt).is_err(), "corrupt JSON is an error");
        let future = dir.path().join("future.json");
        std::fs::write(&future, r#"{ "format": 99, "installs": [] }"#).unwrap();
        assert!(load(&future).is_err(), "an unknown format is an error");
    }

    #[test]
    fn upsert_replaces_only_the_matching_key() {
        let mut receipt = Receipt::default();
        receipt.upsert(record("claude-code", "user", None));
        receipt.upsert(record("codex", "user", None));
        receipt.upsert(record("claude-code", "project", Some("/a/repo")));
        assert_eq!(receipt.installs.len(), 3, "three distinct keys");

        // Replacing the user-scope claude-code entry keeps the count.
        let mut newer = record("claude-code", "user", None);
        newer.version = "0.5.0".to_string();
        receipt.upsert(newer);
        assert_eq!(receipt.installs.len(), 3);
        assert_eq!(
            receipt.find("claude-code", "user", None).unwrap().version,
            "0.5.0"
        );
        // A different project path is a different key.
        receipt.upsert(record("claude-code", "project", Some("/b/repo")));
        assert_eq!(receipt.installs.len(), 4);
    }

    #[test]
    fn remove_drops_the_matching_entry_and_reports_it() {
        let mut receipt = Receipt::default();
        receipt.upsert(record("claude-code", "user", None));
        assert!(receipt.remove("claude-code", "user", None));
        assert!(
            !receipt.remove("claude-code", "user", None),
            "second remove finds nothing"
        );
        assert!(receipt.installs.is_empty());
    }

    #[test]
    fn sha256_hex_is_the_lowercase_hex_digest() {
        // Known vector: sha256 of the empty input.
        assert_eq!(
            sha256_hex(b""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
    }
}
