/**
 * The generator side's one import guard (M4 Global Constraints): the
 * modules a room is generated by never import the session side - the room
 * diff (`world/diff.ts`), the change reactions (`data/changes.ts`), what a
 * fixture reads (`world/reading.ts`), the wall text's flow (`textFlow.ts`),
 * the sound, the overlays, the renderer or the session - so the same input
 * keeps giving the same room byte for byte whatever the session does with
 * it at run time.
 */

import { describe, expect, it } from "vitest";

/** The generator side, by path. */
const GENERATOR_FILES = [
  "./generate.ts",
  "./props.ts",
  "./sites.ts",
  "./dress.ts",
  "./density.ts",
  "./lamps.ts",
  "./footprints.ts",
  "./heroes.ts",
  "./curios.ts",
  "./neighbours.ts",
  "./variants.ts",
  "./finish.ts",
  "./decals.ts",
  "./folders.ts",
  "./lifts.ts",
  "./deck.ts",
  "./hangar.ts",
  "./hangarShape.ts",
  "./airlock.ts",
  "./bridge.ts",
] as const;

const SOURCES = import.meta.glob<string>(
  [
    "./generate.ts",
    "./props.ts",
    "./sites.ts",
    "./dress.ts",
    "./density.ts",
    "./lamps.ts",
    "./footprints.ts",
    "./heroes.ts",
    "./curios.ts",
    "./neighbours.ts",
    "./variants.ts",
    "./finish.ts",
    "./decals.ts",
    "./folders.ts",
    "./lifts.ts",
    "./deck.ts",
    "./hangar.ts",
    "./hangarShape.ts",
    "./airlock.ts",
    "./bridge.ts",
  ],
  { query: "?raw", import: "default", eager: true },
);

/** Every module specifier a source names in an import or an export. */
function specifiers(src: string): string[] {
  const out: string[] = [];
  const pattern = /\b(?:from\s*|import\s*\(\s*|import\s+)["']([^"']+)["']/g;
  for (const m of src.matchAll(pattern)) if (m[1] !== undefined) out.push(m[1]);
  return out;
}

/**
 * A relative specifier resolved against the importing file, as a path from
 * `fluid/src/game/` with no extension and no trailing `/index`:
 * `./diff.js` from `./generate.ts` is `world/diff`. Null for a package
 * specifier, and for one that climbs out of the game folder (Fluid's own
 * modules, which the guard does not police).
 */
function resolveFrom(importer: string, spec: string): string | null {
  if (!spec.startsWith(".")) return null;
  // Paths from `fluid/src/`: the globbed files live in `game/world/`, and
  // `importer` is `./<file>`, so its own folder parts are dropped with the
  // file name.
  const parts: string[] = ["game", "world"];
  const dirs = importer.split("/").slice(0, -1);
  for (const part of [...dirs, ...spec.split("/")]) {
    if (part === "." || part === "") continue;
    if (part === "..") {
      if (parts.pop() === undefined) return null;
    } else parts.push(part);
  }
  if (parts[0] !== "game" || parts.length < 2) return null;
  const path = parts
    .slice(1)
    .join("/")
    .replace(/\.(?:tsx?|jsx?)$/, "");
  return path.replace(/\/index$/, "");
}

/** The session side, as paths from `fluid/src/game/`; a folder covers what is under it. */
const SESSION_SIDE = [
  "world/diff",
  "world/move",
  "world/malfunction",
  "world/interact",
  "world/reading",
  "world/box",
  "world/arrival",
  "world/station",
  "data/changes",
  "audio",
  "ui",
  "render",
  "session",
  "textFlow",
] as const;

/** True when `importer` may not import `spec` (M4 Global Constraints). */
function forbidden(importer: string, spec: string): boolean {
  const target = resolveFrom(importer, spec);
  if (target === null) return false;
  return SESSION_SIDE.some((s) => target === s || target.startsWith(`${s}/`));
}

describe("the generator side's imports", () => {
  it("resolves a specifier against the importing file before matching", () => {
    // Mutation caught: specifiers matched by spelling, so `./diff.js`,
    // `../world/diff` or `../../game/session` slip past the guard.
    const caught = [
      "./diff",
      "./diff.ts",
      "./diff.js",
      "../world/diff",
      "../world/./diff.js",
      "../data/changes.js",
      "../audio/mixer",
      "../audio",
      "../ui",
      "../ui/keys.js",
      "../render/kit",
      "../session",
      "../../game/session.ts",
      "../textFlow",
      "../textFlow.ts",
      "./reading",
      "../world/reading.js",
    ];
    const allowed = [
      "./sites",
      "./diffs",
      "../core/seed",
      "../data/changesets",
      "../../api/events",
      "vitest",
    ];
    expect(caught.length).toBeGreaterThan(0);
    for (const spec of caught)
      expect(`${spec}: ${forbidden("./generate.ts", spec)}`).toBe(
        `${spec}: true`,
      );
    for (const spec of allowed)
      expect(`${spec}: ${forbidden("./generate.ts", spec)}`).toBe(
        `${spec}: false`,
      );
  });

  it("finds every generator module it guards", () => {
    // Mutation caught: a file dropped from the glob or renamed, so the guard
    // below would pass over it unread.
    expect(GENERATOR_FILES.length).toBeGreaterThan(0);
    expect(Object.keys(SOURCES).sort()).toEqual([...GENERATOR_FILES].sort());
    for (const path of GENERATOR_FILES)
      expect(SOURCES[path]?.length ?? 0).toBeGreaterThan(0);
  });

  it("never reaches the session side", () => {
    // Mutation caught: an `import { diffRooms } from "./diff"` added to
    // generate.ts, or any import of data/changes, audio, ui, render or the
    // session.
    const offenders: string[] = [];
    for (const path of GENERATOR_FILES) {
      const src = SOURCES[path] ?? "";
      const specs = specifiers(src);
      expect(specs.length).toBeGreaterThan(0);
      for (const spec of specs)
        if (forbidden(path, spec)) offenders.push(`${path} imports ${spec}`);
    }
    expect(offenders).toEqual([]);
  });
});
