/**
 * The generator side's one import guard (M4 Global Constraints): the
 * modules a room is generated by never import the session side - the room
 * diff (`world/diff.ts`), the change reactions (`data/changes.ts`), the
 * sound, the overlays, the renderer or the session - so the same input
 * keeps giving the same room byte for byte whatever the session does with
 * it at run time.
 */

import { describe, expect, it } from "vitest";

/** The generator side, by path. */
const GENERATOR_FILES = [
  "./generate.ts",
  "./props.ts",
  "./sites.ts",
  "./dress.ts",
  "./density.ts",
  "./lamps.ts",
  "./footprints.ts",
  "./heroes.ts",
  "./curios.ts",
  "./neighbours.ts",
  "./variants.ts",
  "./finish.ts",
  "./decals.ts",
  "./folders.ts",
  "./lifts.ts",
  "./deck.ts",
  "./hangar.ts",
  "./hangarShape.ts",
  "./airlock.ts",
  "./bridge.ts",
] as const;

const SOURCES = import.meta.glob<string>(
  [
    "./generate.ts",
    "./props.ts",
    "./sites.ts",
    "./dress.ts",
    "./density.ts",
    "./lamps.ts",
    "./footprints.ts",
    "./heroes.ts",
    "./curios.ts",
    "./neighbours.ts",
    "./variants.ts",
    "./finish.ts",
    "./decals.ts",
    "./folders.ts",
    "./lifts.ts",
    "./deck.ts",
    "./hangar.ts",
    "./hangarShape.ts",
    "./airlock.ts",
    "./bridge.ts",
  ],
  { query: "?raw", import: "default", eager: true },
);

/** Every module specifier a source names in an import or an export. */
function specifiers(src: string): string[] {
  const out: string[] = [];
  const pattern = /\b(?:from\s*|import\s*\(\s*|import\s+)["']([^"']+)["']/g;
  for (const m of src.matchAll(pattern)) if (m[1] !== undefined) out.push(m[1]);
  return out;
}

/** True when a generator module may not import this specifier. */
function forbidden(spec: string): boolean {
  const bare = spec.replace(/\.tsx?$/, "");
  return (
    bare === "./diff" ||
    bare === "../data/changes" ||
    spec.startsWith("../audio/") ||
    bare === "../ui" ||
    spec.startsWith("../ui/") ||
    bare === "../render" ||
    spec.startsWith("../render/") ||
    bare === "../session"
  );
}

describe("the generator side's imports", () => {
  it("finds every generator module it guards", () => {
    // Mutation caught: a file dropped from the glob or renamed, so the guard
    // below would pass over it unread.
    expect(GENERATOR_FILES.length).toBeGreaterThan(0);
    expect(Object.keys(SOURCES).sort()).toEqual([...GENERATOR_FILES].sort());
    for (const path of GENERATOR_FILES)
      expect(SOURCES[path]?.length ?? 0).toBeGreaterThan(0);
  });

  it("never reaches the session side", () => {
    // Mutation caught: an `import { diffRooms } from "./diff"` added to
    // generate.ts, or any import of data/changes, audio, ui, render or the
    // session.
    const offenders: string[] = [];
    for (const path of GENERATOR_FILES) {
      const src = SOURCES[path] ?? "";
      const specs = specifiers(src);
      expect(specs.length).toBeGreaterThan(0);
      for (const spec of specs)
        if (forbidden(spec)) offenders.push(`${path} imports ${spec}`);
    }
    expect(offenders).toEqual([]);
  });
});
